In [ ]:
s# ============================================================
# STEP 1: IMPORT LIBRARIES AND LOAD SOURCE DATA
# Smart City Traffic & Accident Analytics
# ============================================================

import pandas as pd
import numpy as np

# Load datasets
traffic_df = pd.read_csv('/content/road_traffic_sensor_data.csv')
accident_df = pd.read_csv('/content/traffic_accident_data.csv')

print("Traffic Sensor Dataset:")
print("Shape:", traffic_df.shape)
print()

print("Accident Dataset:")
print("Shape:", accident_df.shape)

Traffic Sensor Dataset:
Shape: (300, 6)

Accident Dataset:
Shape: (5000, 10)

In [ ]:
# ============================================================
# STEP 2: DATA STRUCTURE AND SAMPLE RECORDS
# Smart City Traffic & Accident Analytics
# ============================================================

print("========== TRAFFIC SENSOR DATA ==========")

print("\nColumn Names:")
print(traffic_df.columns.tolist())

print("\nData Types:")
print(traffic_df.dtypes)

print("\nFirst 5 Records:")
display(traffic_df.head())


print("\n\n========== ACCIDENT DATA ==========")

print("\nColumn Names:")
print(accident_df.columns.tolist())

print("\nData Types:")
print(accident_df.dtypes)

print("\nFirst 5 Records:")
display(accident_df.head())

========== TRAFFIC SENSOR DATA ==========

Column Names:
['Sensor_ID', 'Location', 'Date_Time', 'Vehicle_Count', 'Average_Speed', 'Congestion_Level']

Data Types:
Sensor_ID           object
Location            object
Date_Time           object
Vehicle_Count        int64
Average_Speed        int64
Congestion_Level    object
dtype: object

First 5 Records:

,Sensor_ID,Location,Date_Time,Vehicle_Count,Average_Speed,Congestion_Level
0,a36f14,Downtown,2024-01-01 00:00:00,90,59,High
1,256a39,Downtown,2024-01-01 01:00:00,324,73,Moderate
2,a8a01f,Highway,2024-01-01 02:00:00,61,56,Moderate
3,3036e3,Highway,2024-01-01 03:00:00,90,56,High
4,2b45b1,Residential Zone,2024-01-01 04:00:00,72,77,High

========== ACCIDENT DATA ==========

Column Names:
['Accident_ID', 'Date_Time', 'Location', 'Weather_Condition', 'Road_Condition', 'Vehicle_Type', 'Accident_Severity', 'Number_of_Vehicles', 'Casualties', 'Traffic_Density']

Data Types:
Accident_ID           object
Date_Time             object
Location              object
Weather_Condition     object
Road_Condition        object
Vehicle_Type          object
Accident_Severity     object
Number_of_Vehicles     int64
Casualties             int64
Traffic_Density       object
dtype: object

First 5 Records:

,Accident_ID,Date_Time,Location,Weather_Condition,Road_Condition,Vehicle_Type,Accident_Severity,Number_of_Vehicles,Casualties,Traffic_Density
0,d02b3836,2024-01-01 00:00:00,Suburbs,Fog,Icy,Bus,Minor,2,6,Low
1,694c8577,2024-01-01 01:00:00,Downtown,Clear,Icy,Bus,Minor,2,2,Low
2,e0ed5c55,2024-01-01 02:00:00,Residential Zone,Snow,Dry,Motorcycle,Moderate,4,5,Moderate
3,6a78511a,2024-01-01 03:00:00,Downtown,Fog,Icy,Bicycle,Moderate,3,8,Moderate
4,547bf4c2,2024-01-01 04:00:00,Highway,Storm,Under Construction,Bus,Moderate,4,1,High

In [ ]:
# ============================================================
# STEP 3: DATA QUALITY CHECK
# Smart City Traffic & Accident Analytics
# ============================================================

print("========== TRAFFIC SENSOR DATA ==========")

print("\nMissing Values:")
print(traffic_df.isnull().sum())

print("\nTotal Duplicate Rows:")
print(traffic_df.duplicated().sum())


print("\n\n========== ACCIDENT DATA ==========")

print("\nMissing Values:")
print(accident_df.isnull().sum())

print("\nTotal Duplicate Rows:")
print(accident_df.duplicated().sum())

========== TRAFFIC SENSOR DATA ==========

Missing Values:
Sensor_ID           0
Location            0
Date_Time           0
Vehicle_Count       0
Average_Speed       0
Congestion_Level    0
dtype: int64

Total Duplicate Rows:
0


========== ACCIDENT DATA ==========

Missing Values:
Accident_ID           0
Date_Time             0
Location              0
Weather_Condition     0
Road_Condition        0
Vehicle_Type          0
Accident_Severity     0
Number_of_Vehicles    0
Casualties            0
Traffic_Density       0
dtype: int64

Total Duplicate Rows:
0

In [ ]:
# ============================================================
# STEP 4: UNIQUE ID VALIDATION
# Smart City Traffic & Accident Analytics
# ============================================================

print("========== TRAFFIC SENSOR DATA ==========")

print("Total Records:", len(traffic_df))
print("Unique Sensor_IDs:", traffic_df['Sensor_ID'].nunique())
print("Duplicate Sensor_IDs:", traffic_df['Sensor_ID'].duplicated().sum())


print("\n========== ACCIDENT DATA ==========")

print("Total Records:", len(accident_df))
print("Unique Accident_IDs:", accident_df['Accident_ID'].nunique())
print("Duplicate Accident_IDs:", accident_df['Accident_ID'].duplicated().sum())

========== TRAFFIC SENSOR DATA ==========
Total Records: 300
Unique Sensor_IDs: 300
Duplicate Sensor_IDs: 0

========== ACCIDENT DATA ==========
Total Records: 5000
Unique Accident_IDs: 5000
Duplicate Accident_IDs: 0

In [ ]:
# ============================================================
# STEP 5: DATE-TIME CONVERSION AND COVERAGE
# Smart City Traffic & Accident Analytics
# ============================================================

# Convert Date_Time columns to datetime
traffic_df['Date_Time'] = pd.to_datetime(traffic_df['Date_Time'])
accident_df['Date_Time'] = pd.to_datetime(accident_df['Date_Time'])

print("========== TRAFFIC SENSOR DATA ==========")

print("Data Type:", traffic_df['Date_Time'].dtype)
print("Start Date-Time:", traffic_df['Date_Time'].min())
print("End Date-Time:", traffic_df['Date_Time'].max())
print("Unique Date Values:", traffic_df['Date_Time'].dt.date.nunique())
print("Unique Hours:", traffic_df['Date_Time'].dt.hour.nunique())


print("\n========== ACCIDENT DATA ==========")

print("Data Type:", accident_df['Date_Time'].dtype)
print("Start Date-Time:", accident_df['Date_Time'].min())
print("End Date-Time:", accident_df['Date_Time'].max())
print("Unique Date Values:", accident_df['Date_Time'].dt.date.nunique())
print("Unique Hours:", accident_df['Date_Time'].dt.hour.nunique())

========== TRAFFIC SENSOR DATA ==========
Data Type: datetime64[ns]
Start Date-Time: 2024-01-01 00:00:00
End Date-Time: 2024-01-13 11:00:00
Unique Date Values: 13
Unique Hours: 24

========== ACCIDENT DATA ==========
Data Type: datetime64[ns]
Start Date-Time: 2024-01-01 00:00:00
End Date-Time: 2024-07-27 07:00:00
Unique Date Values: 209
Unique Hours: 24

In [ ]:
# ============================================================
# STEP 6: CATEGORICAL VALUE VALIDATION
# Smart City Traffic & Accident Analytics
# ============================================================

print("========== TRAFFIC SENSOR DATA ==========")

print("\nLocations:")
print(sorted(traffic_df['Location'].unique()))

print("\nCongestion Levels:")
print(sorted(traffic_df['Congestion_Level'].unique()))


print("\n\n========== ACCIDENT DATA ==========")

print("\nLocations:")
print(sorted(accident_df['Location'].unique()))

print("\nWeather Conditions:")
print(sorted(accident_df['Weather_Condition'].unique()))

print("\nRoad Conditions:")
print(sorted(accident_df['Road_Condition'].unique()))

print("\nVehicle Types:")
print(sorted(accident_df['Vehicle_Type'].unique()))

print("\nAccident Severity:")
print(sorted(accident_df['Accident_Severity'].unique()))

print("\nTraffic Density:")
print(sorted(accident_df['Traffic_Density'].unique()))

========== TRAFFIC SENSOR DATA ==========

Locations:
['Downtown', 'Highway', 'Industrial Area', 'Residential Zone', 'Suburbs']

Congestion Levels:
['High', 'Low', 'Moderate']


========== ACCIDENT DATA ==========

Locations:
['Downtown', 'Highway', 'Industrial Area', 'Residential Zone', 'Suburbs']

Weather Conditions:
['Clear', 'Fog', 'Rain', 'Snow', 'Storm']

Road Conditions:
['Dry', 'Icy', 'Under Construction', 'Wet']

Vehicle Types:
['Bicycle', 'Bus', 'Car', 'Motorcycle', 'Truck']

Accident Severity:
['Fatal', 'Minor', 'Moderate', 'Severe']

Traffic Density:
['High', 'Low', 'Moderate']

In [ ]:
# ============================================================
# STEP 7: NUMERIC VALUE VALIDATION
# Smart City Traffic & Accident Analytics
# ============================================================

print("========== TRAFFIC SENSOR DATA ==========")

print("\nVehicle Count Statistics:")
print(traffic_df['Vehicle_Count'].describe())

print("\nAverage Speed Statistics:")
print(traffic_df['Average_Speed'].describe())


print("\n\n========== ACCIDENT DATA ==========")

print("\nNumber of Vehicles Statistics:")
print(accident_df['Number_of_Vehicles'].describe())

print("\nCasualties Statistics:")
print(accident_df['Casualties'].describe())

========== TRAFFIC SENSOR DATA ==========

Vehicle Count Statistics:
count    300.000000
mean     278.743333
std      125.767174
min       52.000000
25%      176.500000
50%      284.500000
75%      384.250000
max      494.000000
Name: Vehicle_Count, dtype: float64

Average Speed Statistics:
count    300.000000
mean      49.100000
std       17.890694
min       20.000000
25%       33.000000
50%       48.000000
75%       64.000000
max       79.000000
Name: Average_Speed, dtype: float64


========== ACCIDENT DATA ==========

Number of Vehicles Statistics:
count    5000.000000
mean        2.518200
std         1.107932
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: Number_of_Vehicles, dtype: float64

Casualties Statistics:
count    5000.000000
mean        4.493400
std         2.885069
min         0.000000
25%         2.000000
50%         4.000000
75%         7.000000
max         9.000000
Name: Casualties, dtype: float64

In [ ]:
# ============================================================
# STEP 8: TIMESTAMP VALIDATION
# Smart City Traffic & Accident Analytics
# ============================================================

print("========== TRAFFIC SENSOR DATA ==========")

print("Duplicate Date_Time values:", traffic_df['Date_Time'].duplicated().sum())
print("Chronologically Sorted:", traffic_df['Date_Time'].is_monotonic_increasing)

print("\nFirst 5 Date_Time values:")
print(traffic_df['Date_Time'].head().to_list())

print("\nLast 5 Date_Time values:")
print(traffic_df['Date_Time'].tail().to_list())


print("\n\n========== ACCIDENT DATA ==========")

print("Duplicate Date_Time values:", accident_df['Date_Time'].duplicated().sum())
print("Chronologically Sorted:", accident_df['Date_Time'].is_monotonic_increasing)

print("\nFirst 5 Date_Time values:")
print(accident_df['Date_Time'].head().to_list())

print("\nLast 5 Date_Time values:")
print(accident_df['Date_Time'].tail().to_list())

========== TRAFFIC SENSOR DATA ==========
Duplicate Date_Time values: 0
Chronologically Sorted: True

First 5 Date_Time values:
[Timestamp('2024-01-01 00:00:00'), Timestamp('2024-01-01 01:00:00'), Timestamp('2024-01-01 02:00:00'), Timestamp('2024-01-01 03:00:00'), Timestamp('2024-01-01 04:00:00')]

Last 5 Date_Time values:
[Timestamp('2024-01-13 07:00:00'), Timestamp('2024-01-13 08:00:00'), Timestamp('2024-01-13 09:00:00'), Timestamp('2024-01-13 10:00:00'), Timestamp('2024-01-13 11:00:00')]


========== ACCIDENT DATA ==========
Duplicate Date_Time values: 0
Chronologically Sorted: True

First 5 Date_Time values:
[Timestamp('2024-01-01 00:00:00'), Timestamp('2024-01-01 01:00:00'), Timestamp('2024-01-01 02:00:00'), Timestamp('2024-01-01 03:00:00'), Timestamp('2024-01-01 04:00:00')]

Last 5 Date_Time values:
[Timestamp('2024-07-27 03:00:00'), Timestamp('2024-07-27 04:00:00'), Timestamp('2024-07-27 05:00:00'), Timestamp('2024-07-27 06:00:00'), Timestamp('2024-07-27 07:00:00')]

In [ ]:
# ============================================================
# STEP 9: DATE AND TIME FEATURE ENGINEERING
# Smart City Traffic & Accident Analytics
# ============================================================

# ---------- TRAFFIC DATA ----------

traffic_df['Date'] = traffic_df['Date_Time'].dt.date
traffic_df['Year'] = traffic_df['Date_Time'].dt.year
traffic_df['Month'] = traffic_df['Date_Time'].dt.month
traffic_df['Month_Name'] = traffic_df['Date_Time'].dt.month_name()
traffic_df['Day'] = traffic_df['Date_Time'].dt.day
traffic_df['Day_Name'] = traffic_df['Date_Time'].dt.day_name()
traffic_df['Week'] = traffic_df['Date_Time'].dt.isocalendar().week.astype(int)
traffic_df['Quarter'] = traffic_df['Date_Time'].dt.quarter
traffic_df['Hour'] = traffic_df['Date_Time'].dt.hour

traffic_df['Is_Weekend'] = traffic_df['Date_Time'].dt.dayofweek >= 5


# ---------- ACCIDENT DATA ----------

accident_df['Date'] = accident_df['Date_Time'].dt.date
accident_df['Year'] = accident_df['Date_Time'].dt.year
accident_df['Month'] = accident_df['Date_Time'].dt.month
accident_df['Month_Name'] = accident_df['Date_Time'].dt.month_name()
accident_df['Day'] = accident_df['Date_Time'].dt.day
accident_df['Day_Name'] = accident_df['Date_Time'].dt.day_name()
accident_df['Week'] = accident_df['Date_Time'].dt.isocalendar().week.astype(int)
accident_df['Quarter'] = accident_df['Date_Time'].dt.quarter
accident_df['Hour'] = accident_df['Date_Time'].dt.hour

accident_df['Is_Weekend'] = accident_df['Date_Time'].dt.dayofweek >= 5


print("Traffic Dataset:")
display(
    traffic_df[
        ['Date_Time', 'Date', 'Year', 'Month', 'Month_Name',
         'Day', 'Day_Name', 'Week', 'Quarter', 'Hour', 'Is_Weekend']
    ].head()
)

print("\nAccident Dataset:")
display(
    accident_df[
        ['Date_Time', 'Date', 'Year', 'Month', 'Month_Name',
         'Day', 'Day_Name', 'Week', 'Quarter', 'Hour', 'Is_Weekend']
    ].head()
)

Traffic Dataset:

,Date_Time,Date,Year,Month,Month_Name,Day,Day_Name,Week,Quarter,Hour,Is_Weekend
0,2024-01-01 00:00:00,2024-01-01,2024,1,January,1,Monday,1,1,0,False
1,2024-01-01 01:00:00,2024-01-01,2024,1,January,1,Monday,1,1,1,False
2,2024-01-01 02:00:00,2024-01-01,2024,1,January,1,Monday,1,1,2,False
3,2024-01-01 03:00:00,2024-01-01,2024,1,January,1,Monday,1,1,3,False
4,2024-01-01 04:00:00,2024-01-01,2024,1,January,1,Monday,1,1,4,False

Accident Dataset:

,Date_Time,Date,Year,Month,Month_Name,Day,Day_Name,Week,Quarter,Hour,Is_Weekend
0,2024-01-01 00:00:00,2024-01-01,2024,1,January,1,Monday,1,1,0,False
1,2024-01-01 01:00:00,2024-01-01,2024,1,January,1,Monday,1,1,1,False
2,2024-01-01 02:00:00,2024-01-01,2024,1,January,1,Monday,1,1,2,False
3,2024-01-01 03:00:00,2024-01-01,2024,1,January,1,Monday,1,1,3,False
4,2024-01-01 04:00:00,2024-01-01,2024,1,January,1,Monday,1,1,4,False

In [ ]:
# ============================================================
# STEP 10: TIME PERIOD AND PEAK HOUR FEATURE ENGINEERING
# Smart City Traffic & Accident Analytics
# ============================================================

def get_time_period(hour):
    if 0 <= hour <= 5:
        return 'Night'
    elif 6 <= hour <= 11:
        return 'Morning'
    elif 12 <= hour <= 16:
        return 'Afternoon'
    elif 17 <= hour <= 20:
        return 'Evening'
    else:
        return 'Late Evening'


def get_peak_hour(hour):
    if 7 <= hour <= 9 or 17 <= hour <= 19:
        return 'Peak'
    else:
        return 'Non-Peak'


# Apply to Traffic Dataset
traffic_df['Time_Period'] = traffic_df['Hour'].apply(get_time_period)
traffic_df['Peak_Hour'] = traffic_df['Hour'].apply(get_peak_hour)


# Apply to Accident Dataset
accident_df['Time_Period'] = accident_df['Hour'].apply(get_time_period)
accident_df['Peak_Hour'] = accident_df['Hour'].apply(get_peak_hour)


print("========== TRAFFIC DATA ==========")

print("\nTime Period Distribution:")
print(traffic_df['Time_Period'].value_counts())

print("\nPeak Hour Distribution:")
print(traffic_df['Peak_Hour'].value_counts())


print("\n\n========== ACCIDENT DATA ==========")

print("\nTime Period Distribution:")
print(accident_df['Time_Period'].value_counts())

print("\nPeak Hour Distribution:")
print(accident_df['Peak_Hour'].value_counts())


print("\n\nSample Traffic Records:")
display(
    traffic_df[
        ['Date_Time', 'Hour', 'Time_Period', 'Peak_Hour']
    ].head(15)
)

========== TRAFFIC DATA ==========

Time Period Distribution:
Time_Period
Night           78
Morning         78
Afternoon       60
Evening         48
Late Evening    36
Name: count, dtype: int64

Peak Hour Distribution:
Peak_Hour
Non-Peak    225
Peak         75
Name: count, dtype: int64


========== ACCIDENT DATA ==========

Time Period Distribution:
Time_Period
Night           1254
Morning         1250
Afternoon       1040
Evening          832
Late Evening     624
Name: count, dtype: int64

Peak Hour Distribution:
Peak_Hour
Non-Peak    3751
Peak        1249
Name: count, dtype: int64


Sample Traffic Records:

             Date_Time  Hour Time_Period Peak_Hour
0  2024-01-01 00:00:00     0       Night  Non-Peak
1  2024-01-01 01:00:00     1       Night  Non-Peak
2  2024-01-01 02:00:00     2       Night  Non-Peak
3  2024-01-01 03:00:00     3       Night  Non-Peak
4  2024-01-01 04:00:00     4       Night  Non-Peak
5  2024-01-01 05:00:00     5       Night  Non-Peak
6  2024-01-01 06:00:00     6     Morning  Non-Peak
7  2024-01-01 07:00:00     7     Morning      Peak
8  2024-01-01 08:00:00     8     Morning      Peak
9  2024-01-01 09:00:00     9     Morning      Peak
10 2024-01-01 10:00:00    10     Morning  Non-Peak
11 2024-01-01 11:00:00    11     Morning  Non-Peak
12 2024-01-01 12:00:00    12   Afternoon  Non-Peak
13 2024-01-01 13:00:00    13   Afternoon  Non-Peak
14 2024-01-01 14:00:00    14   Afternoon  Non-Peak

In [ ]:
# ============================================================
# STEP 11: CONGESTION INDEX FEATURE ENGINEERING
# Smart City Traffic & Accident Analytics
# ============================================================

# Calculate Congestion Index
traffic_df['Congestion_Index'] = (
    traffic_df['Vehicle_Count'] / traffic_df['Average_Speed']
)

# Create categories based on the Congestion Index distribution
traffic_df['Congestion_Category'] = pd.qcut(
    traffic_df['Congestion_Index'],
    q=3,
    labels=['Low', 'Moderate', 'High']
)


print("========== CONGESTION INDEX ==========")

print("\nCongestion Index Statistics:")
print(traffic_df['Congestion_Index'].describe())

print("\nCongestion Category Distribution:")
print(traffic_df['Congestion_Category'].value_counts().sort_index())


print("\nSample Records:")
display(
    traffic_df[
        [
            'Location',
            'Date_Time',
            'Vehicle_Count',
            'Average_Speed',
            'Congestion_Level',
            'Congestion_Index',
            'Congestion_Category'
        ]
    ].head(10)
)

========== CONGESTION INDEX ==========

Congestion Index Statistics:
count    300.000000
mean       6.778093
std        4.592042
min        0.833333
25%        3.438538
50%        5.660425
75%        8.698138
max       22.850000
Name: Congestion_Index, dtype: float64

Congestion Category Distribution:
Congestion_Category
Low         100
Moderate    100
High        100
Name: count, dtype: int64

Sample Records:

,Location,Date_Time,Vehicle_Count,Average_Speed,Congestion_Level,Congestion_Index,Congestion_Category
0,Downtown,2024-01-01 00:00:00,90,59,High,1.525424,Low
1,Downtown,2024-01-01 01:00:00,324,73,Moderate,4.438356,Moderate
2,Highway,2024-01-01 02:00:00,61,56,Moderate,1.089286,Low
3,Highway,2024-01-01 03:00:00,90,56,High,1.607143,Low
4,Residential Zone,2024-01-01 04:00:00,72,77,High,0.935065,Low
5,Downtown,2024-01-01 05:00:00,243,61,Moderate,3.983607,Low
6,Residential Zone,2024-01-01 06:00:00,353,74,Moderate,4.770270,Moderate
7,Industrial Area,2024-01-01 07:00:00,475,46,High,10.326087,High
8,Highway,2024-01-01 08:00:00,61,53,Moderate,1.150943,Low
9,Suburbs,2024-01-01 09:00:00,375,44,Low,8.522727,High

In [ ]:
# ============================================================
# STEP 12: ACCIDENT SEVERITY SCORE FEATURE ENGINEERING
# Smart City Traffic & Accident Analytics
# ============================================================

# Map accident severity to an analytical numeric score
severity_score_map = {
    'Minor': 1,
    'Moderate': 2,
    'Severe': 3,
    'Fatal': 4
}

accident_df['Accident_Severity_Score'] = (
    accident_df['Accident_Severity'].map(severity_score_map)
)

print("========== ACCIDENT SEVERITY SCORE ==========")

print("\nSeverity Score Distribution:")
print(
    accident_df[
        ['Accident_Severity', 'Accident_Severity_Score']
    ].drop_duplicates().sort_values('Accident_Severity_Score')
)

print("\nAccident Severity Counts:")
print(
    accident_df['Accident_Severity']
    .value_counts()
)

print("\nAccident Severity Score Statistics:")
print(
    accident_df['Accident_Severity_Score'].describe()
)

print("\nSample Records:")
display(
    accident_df[
        [
            'Accident_ID',
            'Date_Time',
            'Location',
            'Accident_Severity',
            'Accident_Severity_Score',
            'Number_of_Vehicles',
            'Casualties',
            'Traffic_Density'
        ]
    ].head(10)
)

========== ACCIDENT SEVERITY SCORE ==========

Severity Score Distribution:
  Accident_Severity  Accident_Severity_Score
0             Minor                        1
2          Moderate                        2
9            Severe                        3
5             Fatal                        4

Accident Severity Counts:
Accident_Severity
Minor       1262
Fatal       1253
Moderate    1248
Severe      1237
Name: count, dtype: int64

Accident Severity Score Statistics:
count    5000.00000
mean        2.49620
std         1.12082
min         1.00000
25%         1.00000
50%         2.00000
75%         4.00000
max         4.00000
Name: Accident_Severity_Score, dtype: float64

Sample Records:

,Accident_ID,Date_Time,Location,Accident_Severity,Accident_Severity_Score,Number_of_Vehicles,Casualties,Traffic_Density
0,d02b3836,2024-01-01 00:00:00,Suburbs,Minor,1,2,6,Low
1,694c8577,2024-01-01 01:00:00,Downtown,Minor,1,2,2,Low
2,e0ed5c55,2024-01-01 02:00:00,Residential Zone,Moderate,2,4,5,Moderate
3,6a78511a,2024-01-01 03:00:00,Downtown,Moderate,2,3,8,Moderate
4,547bf4c2,2024-01-01 04:00:00,Highway,Moderate,2,4,1,High
5,1c7306c7,2024-01-01 05:00:00,Suburbs,Fatal,4,2,8,Moderate
6,a5557a6b,2024-01-01 06:00:00,Suburbs,Moderate,2,4,5,Moderate
7,3ee0c9e2,2024-01-01 07:00:00,Downtown,Moderate,2,2,8,Low
8,f41e8530,2024-01-01 08:00:00,Suburbs,Moderate,2,2,1,High
9,6967fadc,2024-01-01 09:00:00,Highway,Severe,3,3,7,High

In [ ]:
# ============================================================
# STEP 13: CREATE DATE DIMENSION
# Smart City Traffic & Accident Analytics
# ============================================================

# Combine dates from both datasets
all_dates = pd.concat([
    traffic_df['Date_Time'].dt.normalize(),
    accident_df['Date_Time'].dt.normalize()
]).drop_duplicates().sort_values()

# Create Date Dimension
dim_date = pd.DataFrame({
    'Full_Date': all_dates
})

dim_date['Date_Key'] = (
    dim_date['Full_Date'].dt.strftime('%Y%m%d').astype(int)
)

dim_date['Day'] = dim_date['Full_Date'].dt.day
dim_date['Day_Name'] = dim_date['Full_Date'].dt.day_name()
dim_date['Week'] = dim_date['Full_Date'].dt.isocalendar().week.astype(int)
dim_date['Month'] = dim_date['Full_Date'].dt.month
dim_date['Month_Name'] = dim_date['Full_Date'].dt.month_name()
dim_date['Quarter'] = dim_date['Full_Date'].dt.quarter
dim_date['Year'] = dim_date['Full_Date'].dt.year
dim_date['Is_Weekend'] = (
    dim_date['Full_Date'].dt.dayofweek >= 5
)

# Reorder columns
dim_date = dim_date[
    [
        'Date_Key',
        'Full_Date',
        'Day',
        'Day_Name',
        'Week',
        'Month',
        'Month_Name',
        'Quarter',
        'Year',
        'Is_Weekend'
    ]
]

print("========== DATE DIMENSION ==========")

print("\nShape:")
print(dim_date.shape)

print("\nDate Range:")
print(dim_date['Full_Date'].min(), "to", dim_date['Full_Date'].max())

print("\nColumns:")
print(dim_date.columns.tolist())

print("\nSample Records:")
display(dim_date.head(10))

print("\nDate Dimension Validation:")
print("Duplicate Date_Key:", dim_date['Date_Key'].duplicated().sum())
print("Missing Values:")
print(dim_date.isnull().sum())

========== DATE DIMENSION ==========

Shape:
(209, 10)

Date Range:
2024-01-01 00:00:00 to 2024-07-27 00:00:00

Columns:
['Date_Key', 'Full_Date', 'Day', 'Day_Name', 'Week', 'Month', 'Month_Name', 'Quarter', 'Year', 'Is_Weekend']

Sample Records:

,Date_Key,Full_Date,Day,Day_Name,Week,Month,Month_Name,Quarter,Year,Is_Weekend
0,20240101,2024-01-01,1,Monday,1,1,January,1,2024,False
24,20240102,2024-01-02,2,Tuesday,1,1,January,1,2024,False
48,20240103,2024-01-03,3,Wednesday,1,1,January,1,2024,False
72,20240104,2024-01-04,4,Thursday,1,1,January,1,2024,False
96,20240105,2024-01-05,5,Friday,1,1,January,1,2024,False
120,20240106,2024-01-06,6,Saturday,1,1,January,1,2024,True
144,20240107,2024-01-07,7,Sunday,1,1,January,1,2024,True
168,20240108,2024-01-08,8,Monday,2,1,January,1,2024,False
192,20240109,2024-01-09,9,Tuesday,2,1,January,1,2024,False
216,20240110,2024-01-10,10,Wednesday,2,1,January,1,2024,False

Date Dimension Validation:
Duplicate Date_Key: 0
Missing Values:
Date_Key      0
Full_Date     0
Day           0
Day_Name      0
Week          0
Month         0
Month_Name    0
Quarter       0
Year          0
Is_Weekend    0
dtype: int64

In [ ]:
# ============================================================
# STEP 14: CREATE TIME DIMENSION
# Smart City Traffic & Accident Analytics
# ============================================================

# Create one record for each hour of the day
dim_time = pd.DataFrame({
    'Hour': range(24)
})

# Create time dimension attributes
dim_time['Time_Key'] = dim_time['Hour']
dim_time['Time'] = pd.to_datetime(
    dim_time['Hour'].astype(str).str.zfill(2) + ':00',
    format='%H:%M'
).dt.strftime('%H:%M:%S')

dim_time['Hour_Label'] = (
    dim_time['Hour'].astype(str).str.zfill(2) + ':00'
)

# Reuse the time-period and peak-hour definitions
dim_time['Time_Period'] = dim_time['Hour'].apply(
    get_time_period
)

dim_time['Peak_Hour'] = dim_time['Hour'].apply(
    get_peak_hour
)

# Arrange columns
dim_time = dim_time[
    [
        'Time_Key',
        'Time',
        'Hour',
        'Hour_Label',
        'Time_Period',
        'Peak_Hour'
    ]
]

print("========== TIME DIMENSION ==========")

print("\nShape:")
print(dim_time.shape)

print("\nColumns:")
print(dim_time.columns.tolist())

print("\nTime Period Distribution:")
print(dim_time['Time_Period'].value_counts())

print("\nPeak Hour Distribution:")
print(dim_time['Peak_Hour'].value_counts())

print("\nSample Records:")
display(dim_time.head(10))

print("\nLast 5 Records:")
display(dim_time.tail(5))

print("\nTime Dimension Validation:")
print("Duplicate Time_Key:", dim_time['Time_Key'].duplicated().sum())
print("Missing Values:")
print(dim_time.isnull().sum())

========== TIME DIMENSION ==========

Shape:
(24, 6)

Columns:
['Time_Key', 'Time', 'Hour', 'Hour_Label', 'Time_Period', 'Peak_Hour']

Time Period Distribution:
Time_Period
Night           6
Morning         6
Afternoon       5
Evening         4
Late Evening    3
Name: count, dtype: int64

Peak Hour Distribution:
Peak_Hour
Non-Peak    18
Peak         6
Name: count, dtype: int64

Sample Records:

   Time_Key      Time  Hour Hour_Label Time_Period Peak_Hour
0         0  00:00:00     0      00:00       Night  Non-Peak
1         1  01:00:00     1      01:00       Night  Non-Peak
2         2  02:00:00     2      02:00       Night  Non-Peak
3         3  03:00:00     3      03:00       Night  Non-Peak
4         4  04:00:00     4      04:00       Night  Non-Peak
5         5  05:00:00     5      05:00       Night  Non-Peak
6         6  06:00:00     6      06:00     Morning  Non-Peak
7         7  07:00:00     7      07:00     Morning      Peak
8         8  08:00:00     8      08:00     Morning      Peak
9         9  09:00:00     9      09:00     Morning      Peak

Last 5 Records:

    Time_Key      Time  Hour Hour_Label   Time_Period Peak_Hour
19        19  19:00:00    19      19:00       Evening      Peak
20        20  20:00:00    20      20:00       Evening  Non-Peak
21        21  21:00:00    21      21:00  Late Evening  Non-Peak
22        22  22:00:00    22      22:00  Late Evening  Non-Peak
23        23  23:00:00    23      23:00  Late Evening  Non-Peak

Time Dimension Validation:
Duplicate Time_Key: 0
Missing Values:
Time_Key       0
Time           0
Hour           0
Hour_Label     0
Time_Period    0
Peak_Hour      0
dtype: int64

In [ ]:
# ============================================================
# STEP 15: CREATE WEATHER DIMENSION
# Smart City Traffic & Accident Analytics
# ============================================================

# Extract unique weather conditions
dim_weather = pd.DataFrame({
    'Weather_Condition': sorted(
        accident_df['Weather_Condition'].unique()
    )
})

# Create surrogate key
dim_weather.insert(
    0,
    'Weather_Key',
    range(1, len(dim_weather) + 1)
)

print("========== WEATHER DIMENSION ==========")

print("\nShape:")
print(dim_weather.shape)

print("\nColumns:")
print(dim_weather.columns.tolist())

print("\nWeather Conditions:")
print(dim_weather['Weather_Condition'].tolist())

print("\nSample Records:")
display(dim_weather)

print("\nWeather Dimension Validation:")
print(
    "Duplicate Weather_Key:",
    dim_weather['Weather_Key'].duplicated().sum()
)

print(
    "Duplicate Weather_Condition:",
    dim_weather['Weather_Condition'].duplicated().sum()
)

print("\nMissing Values:")
print(dim_weather.isnull().sum())

========== WEATHER DIMENSION ==========

Shape:
(5, 2)

Columns:
['Weather_Key', 'Weather_Condition']

Weather Conditions:
['Clear', 'Fog', 'Rain', 'Snow', 'Storm']

Sample Records:

   Weather_Key Weather_Condition
0            1             Clear
1            2               Fog
2            3              Rain
3            4              Snow
4            5             Storm

Weather Dimension Validation:
Duplicate Weather_Key: 0
Duplicate Weather_Condition: 0

Missing Values:
Weather_Key          0
Weather_Condition    0
dtype: int64

In [ ]:
# ============================================================
# STEP 16: CREATE ROAD CONDITION DIMENSION
# Smart City Traffic & Accident Analytics
# ============================================================

# Extract unique road conditions
dim_road_condition = pd.DataFrame({
    'Road_Condition': sorted(
        accident_df['Road_Condition'].unique()
    )
})

# Create surrogate key
dim_road_condition.insert(
    0,
    'Road_Condition_Key',
    range(1, len(dim_road_condition) + 1)
)

print("========== ROAD CONDITION DIMENSION ==========")

print("\nShape:")
print(dim_road_condition.shape)

print("\nColumns:")
print(dim_road_condition.columns.tolist())

print("\nRoad Conditions:")
print(dim_road_condition['Road_Condition'].tolist())

print("\nSample Records:")
display(dim_road_condition)

print("\nRoad Condition Dimension Validation:")
print(
    "Duplicate Road_Condition_Key:",
    dim_road_condition['Road_Condition_Key'].duplicated().sum()
)

print(
    "Duplicate Road_Condition:",
    dim_road_condition['Road_Condition'].duplicated().sum()
)

print("\nMissing Values:")
print(dim_road_condition.isnull().sum())

========== ROAD CONDITION DIMENSION ==========

Shape:
(4, 2)

Columns:
['Road_Condition_Key', 'Road_Condition']

Road Conditions:
['Dry', 'Icy', 'Under Construction', 'Wet']

Sample Records:

   Road_Condition_Key      Road_Condition
0                   1                 Dry
1                   2                 Icy
2                   3  Under Construction
3                   4                 Wet

Road Condition Dimension Validation:
Duplicate Road_Condition_Key: 0
Duplicate Road_Condition: 0

Missing Values:
Road_Condition_Key    0
Road_Condition        0
dtype: int64

In [ ]:
# ============================================================
# STEP 17: CREATE VEHICLE TYPE DIMENSION
# Smart City Traffic & Accident Analytics
# ============================================================

# Extract unique vehicle types
dim_vehicle_type = pd.DataFrame({
    'Vehicle_Type': sorted(
        accident_df['Vehicle_Type'].unique()
    )
})

# Create surrogate key
dim_vehicle_type.insert(
    0,
    'Vehicle_Type_Key',
    range(1, len(dim_vehicle_type) + 1)
)

print("========== VEHICLE TYPE DIMENSION ==========")

print("\nShape:")
print(dim_vehicle_type.shape)

print("\nColumns:")
print(dim_vehicle_type.columns.tolist())

print("\nVehicle Types:")
print(dim_vehicle_type['Vehicle_Type'].tolist())

print("\nSample Records:")
display(dim_vehicle_type)

print("\nVehicle Type Dimension Validation:")
print(
    "Duplicate Vehicle_Type_Key:",
    dim_vehicle_type['Vehicle_Type_Key'].duplicated().sum()
)

print(
    "Duplicate Vehicle_Type:",
    dim_vehicle_type['Vehicle_Type'].duplicated().sum()
)

print("\nMissing Values:")
print(dim_vehicle_type.isnull().sum())

========== VEHICLE TYPE DIMENSION ==========

Shape:
(5, 2)

Columns:
['Vehicle_Type_Key', 'Vehicle_Type']

Vehicle Types:
['Bicycle', 'Bus', 'Car', 'Motorcycle', 'Truck']

Sample Records:

   Vehicle_Type_Key Vehicle_Type
0                 1      Bicycle
1                 2          Bus
2                 3          Car
3                 4   Motorcycle
4                 5        Truck

Vehicle Type Dimension Validation:
Duplicate Vehicle_Type_Key: 0
Duplicate Vehicle_Type: 0

Missing Values:
Vehicle_Type_Key    0
Vehicle_Type        0
dtype: int64

In [ ]:
# ============================================================
# STEP 18: CREATE FACT TRAFFIC TABLE
# Smart City Traffic & Accident Analytics
# ============================================================

# Create Fact_Traffic from traffic sensor data
fact_traffic = traffic_df[
    [
        'Date_Time',
        'Sensor_ID',
        'Location',
        'Vehicle_Count',
        'Average_Speed',
        'Congestion_Level',
        'Congestion_Index',
        'Congestion_Category'
    ]
].copy()

# Create Date_Key
fact_traffic['Date_Key'] = (
    fact_traffic['Date_Time']
    .dt.strftime('%Y%m%d')
    .astype(int)
)

# Create Time_Key
fact_traffic['Time_Key'] = (
    fact_traffic['Date_Time'].dt.hour
)

# Create a surrogate Fact key
fact_traffic.insert(
    0,
    'Traffic_Key',
    range(1, len(fact_traffic) + 1)
)

# Arrange columns according to the dimensional model
fact_traffic = fact_traffic[
    [
        'Traffic_Key',
        'Date_Key',
        'Time_Key',
        'Sensor_ID',
        'Location',
        'Vehicle_Count',
        'Average_Speed',
        'Congestion_Level',
        'Congestion_Index',
        'Congestion_Category',
        'Date_Time'
    ]
]

print("========== FACT TRAFFIC ==========")

print("\nShape:")
print(fact_traffic.shape)

print("\nColumns:")
print(fact_traffic.columns.tolist())

print("\nSample Records:")
display(fact_traffic.head(10))

print("\nFact Traffic Validation:")
print(
    "Duplicate Traffic_Key:",
    fact_traffic['Traffic_Key'].duplicated().sum()
)

print(
    "Missing Values:"
)
print(fact_traffic.isnull().sum())

print("\nDate Key Validation:")
print(
    "Invalid Date_Key:",
    (~fact_traffic['Date_Key'].isin(dim_date['Date_Key'])).sum()
)

print("\nTime Key Validation:")
print(
    "Invalid Time_Key:",
    (~fact_traffic['Time_Key'].isin(dim_time['Time_Key'])).sum()
)

========== FACT TRAFFIC ==========

Shape:
(300, 11)

Columns:
['Traffic_Key', 'Date_Key', 'Time_Key', 'Sensor_ID', 'Location', 'Vehicle_Count', 'Average_Speed', 'Congestion_Level', 'Congestion_Index', 'Congestion_Category', 'Date_Time']

Sample Records:

,Traffic_Key,Date_Key,Time_Key,Sensor_ID,Location,Vehicle_Count,Average_Speed,Congestion_Level,Congestion_Index,Congestion_Category,Date_Time
0,1,20240101,0,a36f14,Downtown,90,59,High,1.525424,Low,2024-01-01 00:00:00
1,2,20240101,1,256a39,Downtown,324,73,Moderate,4.438356,Moderate,2024-01-01 01:00:00
2,3,20240101,2,a8a01f,Highway,61,56,Moderate,1.089286,Low,2024-01-01 02:00:00
3,4,20240101,3,3036e3,Highway,90,56,High,1.607143,Low,2024-01-01 03:00:00
4,5,20240101,4,2b45b1,Residential Zone,72,77,High,0.935065,Low,2024-01-01 04:00:00
5,6,20240101,5,6204a2,Downtown,243,61,Moderate,3.983607,Low,2024-01-01 05:00:00
6,7,20240101,6,10cf13,Residential Zone,353,74,Moderate,4.770270,Moderate,2024-01-01 06:00:00
7,8,20240101,7,839bb8,Industrial Area,475,46,High,10.326087,High,2024-01-01 07:00:00
8,9,20240101,8,01274a,Highway,61,53,Moderate,1.150943,Low,2024-01-01 08:00:00
9,10,20240101,9,d0bc93,Suburbs,375,44,Low,8.522727,High,2024-01-01 09:00:00

Fact Traffic Validation:
Duplicate Traffic_Key: 0
Missing Values:
Traffic_Key            0
Date_Key               0
Time_Key               0
Sensor_ID              0
Location               0
Vehicle_Count          0
Average_Speed          0
Congestion_Level       0
Congestion_Index       0
Congestion_Category    0
Date_Time              0
dtype: int64

Date Key Validation:
Invalid Date_Key: 0

Time Key Validation:
Invalid Time_Key: 0

In [ ]:
# ============================================================
# STEP 19: CREATE FACT ACCIDENT TABLE
# Smart City Traffic & Accident Analytics
# ============================================================

# Start with the required accident fields
fact_accident = accident_df[
    [
        'Date_Time',
        'Accident_ID',
        'Location',
        'Weather_Condition',
        'Road_Condition',
        'Vehicle_Type',
        'Accident_Severity',
        'Accident_Severity_Score',
        'Number_of_Vehicles',
        'Casualties',
        'Traffic_Density'
    ]
].copy()

# ------------------------------------------------------------
# Create Date_Key
# ------------------------------------------------------------
fact_accident['Date_Key'] = (
    fact_accident['Date_Time']
    .dt.strftime('%Y%m%d')
    .astype(int)
)

# ------------------------------------------------------------
# Create Time_Key
# ------------------------------------------------------------
fact_accident['Time_Key'] = (
    fact_accident['Date_Time'].dt.hour
)

# ------------------------------------------------------------
# Map Weather to Weather_Key
# ------------------------------------------------------------
weather_map = dict(
    zip(
        dim_weather['Weather_Condition'],
        dim_weather['Weather_Key']
    )
)

fact_accident['Weather_Key'] = (
    fact_accident['Weather_Condition'].map(weather_map)
)

# ------------------------------------------------------------
# Map Road Condition to Road_Condition_Key
# ------------------------------------------------------------
road_condition_map = dict(
    zip(
        dim_road_condition['Road_Condition'],
        dim_road_condition['Road_Condition_Key']
    )
)

fact_accident['Road_Condition_Key'] = (
    fact_accident['Road_Condition'].map(
        road_condition_map
    )
)

# ------------------------------------------------------------
# Map Vehicle Type to Vehicle_Type_Key
# ------------------------------------------------------------
vehicle_type_map = dict(
    zip(
        dim_vehicle_type['Vehicle_Type'],
        dim_vehicle_type['Vehicle_Type_Key']
    )
)

fact_accident['Vehicle_Type_Key'] = (
    fact_accident['Vehicle_Type'].map(
        vehicle_type_map
    )
)

# ------------------------------------------------------------
# Create surrogate Fact key
# ------------------------------------------------------------
fact_accident.insert(
    0,
    'Accident_Key',
    range(1, len(fact_accident) + 1)
)

# ------------------------------------------------------------
# Arrange columns according to dimensional model
# ------------------------------------------------------------
fact_accident = fact_accident[
    [
        'Accident_Key',
        'Date_Key',
        'Time_Key',
        'Accident_ID',
        'Location',
        'Weather_Key',
        'Road_Condition_Key',
        'Vehicle_Type_Key',
        'Accident_Severity',
        'Accident_Severity_Score',
        'Number_of_Vehicles',
        'Casualties',
        'Traffic_Density',
        'Date_Time'
    ]
]

print("========== FACT ACCIDENT ==========")

print("\nShape:")
print(fact_accident.shape)

print("\nColumns:")
print(fact_accident.columns.tolist())

print("\nSample Records:")
display(fact_accident.head(10))

print("\nFact Accident Validation:")

print(
    "Duplicate Accident_Key:",
    fact_accident['Accident_Key'].duplicated().sum()
)

print("\nMissing Values:")
print(fact_accident.isnull().sum())

print("\nDate Key Validation:")
print(
    "Invalid Date_Key:",
    (~fact_accident['Date_Key'].isin(
        dim_date['Date_Key']
    )).sum()
)

print("\nTime Key Validation:")
print(
    "Invalid Time_Key:",
    (~fact_accident['Time_Key'].isin(
        dim_time['Time_Key']
    )).sum()
)

print("\nWeather Key Validation:")
print(
    "Invalid Weather_Key:",
    (~fact_accident['Weather_Key'].isin(
        dim_weather['Weather_Key']
    )).sum()
)

print("\nRoad Condition Key Validation:")
print(
    "Invalid Road_Condition_Key:",
    (~fact_accident['Road_Condition_Key'].isin(
        dim_road_condition['Road_Condition_Key']
    )).sum()
)

print("\nVehicle Type Key Validation:")
print(
    "Invalid Vehicle_Type_Key:",
    (~fact_accident['Vehicle_Type_Key'].isin(
        dim_vehicle_type['Vehicle_Type_Key']
    )).sum()
)

========== FACT ACCIDENT ==========

Shape:
(5000, 14)

Columns:
['Accident_Key', 'Date_Key', 'Time_Key', 'Accident_ID', 'Location', 'Weather_Key', 'Road_Condition_Key', 'Vehicle_Type_Key', 'Accident_Severity', 'Accident_Severity_Score', 'Number_of_Vehicles', 'Casualties', 'Traffic_Density', 'Date_Time']

Sample Records:

,Accident_Key,Date_Key,Time_Key,Accident_ID,Location,Weather_Key,Road_Condition_Key,Vehicle_Type_Key,Accident_Severity,Accident_Severity_Score,Number_of_Vehicles,Casualties,Traffic_Density,Date_Time
0,1,20240101,0,d02b3836,Suburbs,2,2,2,Minor,1,2,6,Low,2024-01-01 00:00:00
1,2,20240101,1,694c8577,Downtown,1,2,2,Minor,1,2,2,Low,2024-01-01 01:00:00
2,3,20240101,2,e0ed5c55,Residential Zone,4,1,4,Moderate,2,4,5,Moderate,2024-01-01 02:00:00
3,4,20240101,3,6a78511a,Downtown,2,2,1,Moderate,2,3,8,Moderate,2024-01-01 03:00:00
4,5,20240101,4,547bf4c2,Highway,5,3,2,Moderate,2,4,1,High,2024-01-01 04:00:00
5,6,20240101,5,1c7306c7,Suburbs,1,4,3,Fatal,4,2,8,Moderate,2024-01-01 05:00:00
6,7,20240101,6,a5557a6b,Suburbs,5,2,4,Moderate,2,4,5,Moderate,2024-01-01 06:00:00
7,8,20240101,7,3ee0c9e2,Downtown,2,4,3,Moderate,2,2,8,Low,2024-01-01 07:00:00
8,9,20240101,8,f41e8530,Suburbs,3,1,1,Moderate,2,2,1,High,2024-01-01 08:00:00
9,10,20240101,9,6967fadc,Highway,1,1,2,Severe,3,3,7,High,2024-01-01 09:00:00

Fact Accident Validation:
Duplicate Accident_Key: 0

Missing Values:
Accident_Key               0
Date_Key                   0
Time_Key                   0
Accident_ID                0
Location                   0
Weather_Key                0
Road_Condition_Key         0
Vehicle_Type_Key           0
Accident_Severity          0
Accident_Severity_Score    0
Number_of_Vehicles         0
Casualties                 0
Traffic_Density            0
Date_Time                  0
dtype: int64

Date Key Validation:
Invalid Date_Key: 0

Time Key Validation:
Invalid Time_Key: 0

Weather Key Validation:
Invalid Weather_Key: 0

Road Condition Key Validation:
Invalid Road_Condition_Key: 0

Vehicle Type Key Validation:
Invalid Vehicle_Type_Key: 0

In [ ]:
# ============================================================
# STEP 20: FINAL DIMENSIONAL MODEL VALIDATION
# Smart City Traffic & Accident Analytics
# ============================================================

print("=" * 65)
print("FINAL DIMENSIONAL MODEL VALIDATION")
print("=" * 65)

# ------------------------------------------------------------
# 1. Table Summary
# ------------------------------------------------------------
table_summary = pd.DataFrame({
    'Table': [
        'Dim_Date',
        'Dim_Time',
        'Dim_Weather',
        'Dim_Road_Condition',
        'Dim_Vehicle_Type',
        'Fact_Traffic',
        'Fact_Accident'
    ],
    'Rows': [
        len(dim_date),
        len(dim_time),
        len(dim_weather),
        len(dim_road_condition),
        len(dim_vehicle_type),
        len(fact_traffic),
        len(fact_accident)
    ],
    'Columns': [
        len(dim_date.columns),
        len(dim_time.columns),
        len(dim_weather.columns),
        len(dim_road_condition.columns),
        len(dim_vehicle_type.columns),
        len(fact_traffic.columns),
        len(fact_accident.columns)
    ]
})

print("\n========== TABLE SUMMARY ==========")
display(table_summary)

# ------------------------------------------------------------
# 2. Primary Key Validation
# ------------------------------------------------------------
print("\n========== PRIMARY KEY VALIDATION ==========")

pk_checks = {
    'Dim_Date.Date_Key': dim_date['Date_Key'].duplicated().sum(),
    'Dim_Time.Time_Key': dim_time['Time_Key'].duplicated().sum(),
    'Dim_Weather.Weather_Key': dim_weather['Weather_Key'].duplicated().sum(),
    'Dim_Road_Condition.Road_Condition_Key':
        dim_road_condition['Road_Condition_Key'].duplicated().sum(),
    'Dim_Vehicle_Type.Vehicle_Type_Key':
        dim_vehicle_type['Vehicle_Type_Key'].duplicated().sum(),
    'Fact_Traffic.Traffic_Key':
        fact_traffic['Traffic_Key'].duplicated().sum(),
    'Fact_Accident.Accident_Key':
        fact_accident['Accident_Key'].duplicated().sum()
}

for key, duplicates in pk_checks.items():
    status = "VALID" if duplicates == 0 else "INVALID"
    print(f"{key:<45} {status} | Duplicates: {duplicates}")

# ------------------------------------------------------------
# 3. Foreign Key Validation
# ------------------------------------------------------------
print("\n========== FOREIGN KEY VALIDATION ==========")

fk_checks = {
    'Fact_Traffic.Date_Key → Dim_Date':
        (~fact_traffic['Date_Key'].isin(dim_date['Date_Key'])).sum(),

    'Fact_Traffic.Time_Key → Dim_Time':
        (~fact_traffic['Time_Key'].isin(dim_time['Time_Key'])).sum(),

    'Fact_Accident.Date_Key → Dim_Date':
        (~fact_accident['Date_Key'].isin(dim_date['Date_Key'])).sum(),

    'Fact_Accident.Time_Key → Dim_Time':
        (~fact_accident['Time_Key'].isin(dim_time['Time_Key'])).sum(),

    'Fact_Accident.Weather_Key → Dim_Weather':
        (~fact_accident['Weather_Key'].isin(
            dim_weather['Weather_Key']
        )).sum(),

    'Fact_Accident.Road_Condition_Key → Dim_Road_Condition':
        (~fact_accident['Road_Condition_Key'].isin(
            dim_road_condition['Road_Condition_Key']
        )).sum(),

    'Fact_Accident.Vehicle_Type_Key → Dim_Vehicle_Type':
        (~fact_accident['Vehicle_Type_Key'].isin(
            dim_vehicle_type['Vehicle_Type_Key']
        )).sum()
}

for relationship, invalid in fk_checks.items():
    status = "VALID" if invalid == 0 else "INVALID"
    print(f"{relationship:<55} {status} | Invalid: {invalid}")

# ------------------------------------------------------------
# 4. Missing Value Validation
# ------------------------------------------------------------
print("\n========== MISSING VALUE VALIDATION ==========")

tables = {
    'Dim_Date': dim_date,
    'Dim_Time': dim_time,
    'Dim_Weather': dim_weather,
    'Dim_Road_Condition': dim_road_condition,
    'Dim_Vehicle_Type': dim_vehicle_type,
    'Fact_Traffic': fact_traffic,
    'Fact_Accident': fact_accident
}

for table_name, df in tables.items():
    missing = df.isnull().sum().sum()
    status = "VALID" if missing == 0 else "CHECK"
    print(f"{table_name:<25} {status} | Total Missing Values: {missing}")

# ------------------------------------------------------------
# 5. Overall Model Status
# ------------------------------------------------------------
all_pk_valid = all(value == 0 for value in pk_checks.values())
all_fk_valid = all(value == 0 for value in fk_checks.values())
all_missing_valid = all(
    df.isnull().sum().sum() == 0
    for df in tables.values()
)

print("\n" + "=" * 65)

if all_pk_valid and all_fk_valid and all_missing_valid:
    print("OVERALL MODEL STATUS: VALID")
    print("All dimensions and fact tables are ready for MySQL loading.")
else:
    print("OVERALL MODEL STATUS: CHECK REQUIRED")

print("=" * 65)

=================================================================
FINAL DIMENSIONAL MODEL VALIDATION
=================================================================

========== TABLE SUMMARY ==========

                Table  Rows  Columns
0            Dim_Date   209       10
1            Dim_Time    24        6
2         Dim_Weather     5        2
3  Dim_Road_Condition     4        2
4    Dim_Vehicle_Type     5        2
5        Fact_Traffic   300       11
6       Fact_Accident  5000       14

========== PRIMARY KEY VALIDATION ==========
Dim_Date.Date_Key                             VALID | Duplicates: 0
Dim_Time.Time_Key                             VALID | Duplicates: 0
Dim_Weather.Weather_Key                       VALID | Duplicates: 0
Dim_Road_Condition.Road_Condition_Key         VALID | Duplicates: 0
Dim_Vehicle_Type.Vehicle_Type_Key             VALID | Duplicates: 0
Fact_Traffic.Traffic_Key                      VALID | Duplicates: 0
Fact_Accident.Accident_Key                    VALID | Duplicates: 0

========== FOREIGN KEY VALIDATION ==========
Fact_Traffic.Date_Key → Dim_Date                        VALID | Invalid: 0
Fact_Traffic.Time_Key → Dim_Time                        VALID | Invalid: 0
Fact_Accident.Date_Key → Dim_Date                       VALID | Invalid: 0
Fact_Accident.Time_Key → Dim_Time                       VALID | Invalid: 0
Fact_Accident.Weather_Key → Dim_Weather                 VALID | Invalid: 0
Fact_Accident.Road_Condition_Key → Dim_Road_Condition   VALID | Invalid: 0
Fact_Accident.Vehicle_Type_Key → Dim_Vehicle_Type       VALID | Invalid: 0

========== MISSING VALUE VALIDATION ==========
Dim_Date                  VALID | Total Missing Values: 0
Dim_Time                  VALID | Total Missing Values: 0
Dim_Weather               VALID | Total Missing Values: 0
Dim_Road_Condition        VALID | Total Missing Values: 0
Dim_Vehicle_Type          VALID | Total Missing Values: 0
Fact_Traffic              VALID | Total Missing Values: 0
Fact_Accident             VALID | Total Missing Values: 0

=================================================================
OVERALL MODEL STATUS: VALID
All dimensions and fact tables are ready for MySQL loading.
=================================================================

In [ ]:
# ============================================================
# STEP 21: EXPORT DIMENSIONAL MODEL TABLES
# Smart City Traffic & Accident Analytics
# ============================================================

# Export dimensions
dim_date.to_csv(
    '/content/Dim_Date.csv',
    index=False
)

dim_time.to_csv(
    '/content/Dim_Time.csv',
    index=False
)

dim_weather.to_csv(
    '/content/Dim_Weather.csv',
    index=False
)

dim_road_condition.to_csv(
    '/content/Dim_Road_Condition.csv',
    index=False
)

dim_vehicle_type.to_csv(
    '/content/Dim_Vehicle_Type.csv',
    index=False
)

# Export fact tables
fact_traffic.to_csv(
    '/content/Fact_Traffic.csv',
    index=False
)

fact_accident.to_csv(
    '/content/Fact_Accident.csv',
    index=False
)

# ------------------------------------------------------------
# Verify exported files
# ------------------------------------------------------------

import os

exported_files = [
    'Dim_Date.csv',
    'Dim_Time.csv',
    'Dim_Weather.csv',
    'Dim_Road_Condition.csv',
    'Dim_Vehicle_Type.csv',
    'Fact_Traffic.csv',
    'Fact_Accident.csv'
]

print("========== EXPORTED TABLES ==========")

for file in exported_files:
    path = '/content/' + file
    size_kb = os.path.getsize(path) / 1024

    print(
        f"{file:<25} "
        f"Rows: {pd.read_csv(path).shape[0]:<5} "
        f"Size: {size_kb:.2f} KB"
    )

print("\nTotal Tables Exported:", len(exported_files))
print("\nExport Location: /content/")

========== EXPORTED TABLES ==========
Dim_Date.csv              Rows: 209   Size: 11.18 KB
Dim_Time.csv              Rows: 24    Size: 0.91 KB
Dim_Weather.csv           Rows: 5     Size: 0.06 KB
Dim_Road_Condition.csv    Rows: 4     Size: 0.07 KB
Dim_Vehicle_Type.csv      Rows: 5     Size: 0.07 KB
Fact_Traffic.csv          Rows: 300   Size: 26.09 KB
Fact_Accident.csv         Rows: 5000  Size: 400.51 KB

Total Tables Exported: 7

Export Location: /content/

In [ ]:
# Convert Is_Weekend from True/False to 1/0 for MySQL import

dim_date['Is_Weekend'] = dim_date['Is_Weekend'].astype(int)

# Export the corrected Dim_Date file
dim_date.to_csv('/content/Dim_Date.csv', index=False)

# Verify
print(dim_date[['Full_Date', 'Is_Weekend']].head(10))
print("\nIs_Weekend values:")
print(dim_date['Is_Weekend'].value_counts())
print("\nFile updated successfully.")

     Full_Date  Is_Weekend
0   2024-01-01           0
24  2024-01-02           0
48  2024-01-03           0
72  2024-01-04           0
96  2024-01-05           0
120 2024-01-06           1
144 2024-01-07           1
168 2024-01-08           0
192 2024-01-09           0
216 2024-01-10           0

Is_Weekend values:
Is_Weekend
0    150
1     59
Name: count, dtype: int64

File updated successfully.

In [ ]:
# ============================================================
# STEP 89: PREPARE PREDICTIVE MODELING DATASET
# ============================================================

# Create a copy of the accident dataset
model_df = accident_df.copy()

# Select predictive features and target
model_df = model_df[
    [
        'Location',
        'Weather_Condition',
        'Road_Condition',
        'Vehicle_Type',
        'Traffic_Density',
        'Hour',
        'Time_Period',
        'Peak_Hour',
        'Month',
        'Day_Name',
        'Is_Weekend',
        'Number_of_Vehicles',
        'Casualties',
        'Accident_Severity',
        'Accident_Severity_Score'
    ]
].copy()

print("=" * 70)
print("PREDICTIVE MODELING DATASET")
print("=" * 70)

print("\nDataset Shape:")
print(model_df.shape)

print("\nColumns:")
print(model_df.columns.tolist())

print("\nMissing Values:")
print(model_df.isnull().sum())

print("\nAccident Severity Distribution:")
print(model_df['Accident_Severity'].value_counts())

print("\nAccident Severity Percentage:")
print(
    (model_df['Accident_Severity'].value_counts(normalize=True) * 100)
    .round(2)
)

print("\nSeverity Score Distribution:")
print(model_df['Accident_Severity_Score'].value_counts().sort_index())

print("\nSample Records:")
display(model_df.head())

======================================================================
PREDICTIVE MODELING DATASET
======================================================================

Dataset Shape:
(5000, 15)

Columns:
['Location', 'Weather_Condition', 'Road_Condition', 'Vehicle_Type', 'Traffic_Density', 'Hour', 'Time_Period', 'Peak_Hour', 'Month', 'Day_Name', 'Is_Weekend', 'Number_of_Vehicles', 'Casualties', 'Accident_Severity', 'Accident_Severity_Score']

Missing Values:
Location                   0
Weather_Condition          0
Road_Condition             0
Vehicle_Type               0
Traffic_Density            0
Hour                       0
Time_Period                0
Peak_Hour                  0
Month                      0
Day_Name                   0
Is_Weekend                 0
Number_of_Vehicles         0
Casualties                 0
Accident_Severity          0
Accident_Severity_Score    0
dtype: int64

Accident Severity Distribution:
Accident_Severity
Minor       1262
Fatal       1253
Moderate    1248
Severe      1237
Name: count, dtype: int64

Accident Severity Percentage:
Accident_Severity
Minor       25.24
Fatal       25.06
Moderate    24.96
Severe      24.74
Name: proportion, dtype: float64

Severity Score Distribution:
Accident_Severity_Score
1    1262
2    1248
3    1237
4    1253
Name: count, dtype: int64

Sample Records:

,Location,Weather_Condition,Road_Condition,Vehicle_Type,Traffic_Density,Hour,Time_Period,Peak_Hour,Month,Day_Name,Is_Weekend,Number_of_Vehicles,Casualties,Accident_Severity,Accident_Severity_Score
0,Suburbs,Fog,Icy,Bus,Low,0,Night,Non-Peak,1,Monday,False,2,6,Minor,1
1,Downtown,Clear,Icy,Bus,Low,1,Night,Non-Peak,1,Monday,False,2,2,Minor,1
2,Residential Zone,Snow,Dry,Motorcycle,Moderate,2,Night,Non-Peak,1,Monday,False,4,5,Moderate,2
3,Downtown,Fog,Icy,Bicycle,Moderate,3,Night,Non-Peak,1,Monday,False,3,8,Moderate,2
4,Highway,Storm,Under Construction,Bus,High,4,Night,Non-Peak,1,Monday,False,4,1,Moderate,2

In [ ]:
# ============================================================
# STEP 90: CREATE HIGH-RISK ACCIDENT TARGET
# ============================================================

# Create a modeling copy
risk_df = model_df.copy()

# Create binary target:
# 1 = High Risk (Severe or Fatal)
# 0 = Lower Risk (Minor or Moderate)

risk_df['High_Risk'] = risk_df['Accident_Severity'].isin(
    ['Severe', 'Fatal']
).astype(int)

# Check target distribution
print("=" * 70)
print("HIGH-RISK ACCIDENT TARGET")
print("=" * 70)

print("\nTarget Definition:")
print("1 = Severe or Fatal")
print("0 = Minor or Moderate")

print("\nTarget Distribution:")
print(
    risk_df['High_Risk']
    .value_counts()
    .sort_index()
)

print("\nTarget Percentage:")
print(
    (risk_df['High_Risk']
     .value_counts(normalize=True)
     .sort_index() * 100)
    .round(2)
)

print("\nTarget by Accident Severity:")
print(
    pd.crosstab(
        risk_df['Accident_Severity'],
        risk_df['High_Risk']
    )
)

print("\nModeling Dataset Shape:")
print(risk_df.shape)

print("\nSample:")
display(
    risk_df[
        [
            'Location',
            'Weather_Condition',
            'Road_Condition',
            'Vehicle_Type',
            'Traffic_Density',
            'Hour',
            'Time_Period',
            'Peak_Hour',
            'Month',
            'Day_Name',
            'Is_Weekend',
            'Number_of_Vehicles',
            'Accident_Severity',
            'High_Risk'
        ]
    ].head()
)

======================================================================
HIGH-RISK ACCIDENT TARGET
======================================================================

Target Definition:
1 = Severe or Fatal
0 = Minor or Moderate

Target Distribution:
High_Risk
0    2510
1    2490
Name: count, dtype: int64

Target Percentage:
High_Risk
0    50.2
1    49.8
Name: proportion, dtype: float64

Target by Accident Severity:
High_Risk             0     1
Accident_Severity
Fatal                 0  1253
Minor              1262     0
Moderate           1248     0
Severe                0  1237

Modeling Dataset Shape:
(5000, 16)

Sample:

,Location,Weather_Condition,Road_Condition,Vehicle_Type,Traffic_Density,Hour,Time_Period,Peak_Hour,Month,Day_Name,Is_Weekend,Number_of_Vehicles,Accident_Severity,High_Risk
0,Suburbs,Fog,Icy,Bus,Low,0,Night,Non-Peak,1,Monday,False,2,Minor,0
1,Downtown,Clear,Icy,Bus,Low,1,Night,Non-Peak,1,Monday,False,2,Minor,0
2,Residential Zone,Snow,Dry,Motorcycle,Moderate,2,Night,Non-Peak,1,Monday,False,4,Moderate,0
3,Downtown,Fog,Icy,Bicycle,Moderate,3,Night,Non-Peak,1,Monday,False,3,Moderate,0
4,Highway,Storm,Under Construction,Bus,High,4,Night,Non-Peak,1,Monday,False,4,Moderate,0

In [ ]:
# ============================================================
# STEP 91: TRAIN-TEST SPLIT
# ============================================================

from sklearn.model_selection import train_test_split

# Predictive features
feature_columns = [
    'Location',
    'Weather_Condition',
    'Road_Condition',
    'Vehicle_Type',
    'Traffic_Density',
    'Hour',
    'Time_Period',
    'Peak_Hour',
    'Month',
    'Day_Name',
    'Is_Weekend',
    'Number_of_Vehicles'
]

X = risk_df[feature_columns].copy()
y = risk_df['High_Risk'].copy()

# Stratified 80/20 train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("=" * 70)
print("TRAIN-TEST SPLIT")
print("=" * 70)

print("\nOriginal Dataset:")
print("X:", X.shape)
print("y:", y.shape)

print("\nTraining Dataset:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nTesting Dataset:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("\nTraining Target Distribution:")
print(y_train.value_counts().sort_index())

print("\nTraining Target Percentage:")
print(
    (y_train.value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

print("\nTesting Target Distribution:")
print(y_test.value_counts().sort_index())

print("\nTesting Target Percentage:")
print(
    (y_test.value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

======================================================================
TRAIN-TEST SPLIT
======================================================================

Original Dataset:
X: (5000, 12)
y: (5000,)

Training Dataset:
X_train: (4000, 12)
y_train: (4000,)

Testing Dataset:
X_test: (1000, 12)
y_test: (1000,)

Training Target Distribution:
High_Risk
0    2008
1    1992
Name: count, dtype: int64

Training Target Percentage:
High_Risk
0    50.2
1    49.8
Name: proportion, dtype: float64

Testing Target Distribution:
High_Risk
0    502
1    498
Name: count, dtype: int64

Testing Target Percentage:
High_Risk
0    50.2
1    49.8
Name: proportion, dtype: float64

In [ ]:
# ============================================================
# STEP 92: ENCODE CATEGORICAL VARIABLES
# ============================================================

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Categorical features
categorical_features = [
    'Location',
    'Weather_Condition',
    'Road_Condition',
    'Vehicle_Type',
    'Traffic_Density',
    'Time_Period',
    'Peak_Hour',
    'Day_Name'
]

# Numerical features
numerical_features = [
    'Hour',
    'Month',
    'Is_Weekend',
    'Number_of_Vehicles'
]

# Create preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        (
            'categorical',
            OneHotEncoder(
                handle_unknown='ignore',
                sparse_output=False
            ),
            categorical_features
        ),
        (
            'numerical',
            'passthrough',
            numerical_features
        )
    ]
)

# Fit preprocessing only on training data
X_train_encoded = preprocessor.fit_transform(X_train)

# Transform test data using the same fitted preprocessing
X_test_encoded = preprocessor.transform(X_test)

# Get encoded feature names
encoded_feature_names = preprocessor.get_feature_names_out()

print("=" * 70)
print("CATEGORICAL ENCODING")
print("=" * 70)

print("\nOriginal Training Shape:")
print(X_train.shape)

print("\nEncoded Training Shape:")
print(X_train_encoded.shape)

print("\nOriginal Testing Shape:")
print(X_test.shape)

print("\nEncoded Testing Shape:")
print(X_test_encoded.shape)

print("\nTotal Encoded Features:")
print(len(encoded_feature_names))

print("\nEncoded Feature Names:")
print(encoded_feature_names.tolist())

======================================================================
CATEGORICAL ENCODING
======================================================================

Original Training Shape:
(4000, 12)

Encoded Training Shape:
(4000, 40)

Original Testing Shape:
(1000, 12)

Encoded Testing Shape:
(1000, 40)

Total Encoded Features:
40

Encoded Feature Names:
['categorical__Location_Downtown', 'categorical__Location_Highway', 'categorical__Location_Industrial Area', 'categorical__Location_Residential Zone', 'categorical__Location_Suburbs', 'categorical__Weather_Condition_Clear', 'categorical__Weather_Condition_Fog', 'categorical__Weather_Condition_Rain', 'categorical__Weather_Condition_Snow', 'categorical__Weather_Condition_Storm', 'categorical__Road_Condition_Dry', 'categorical__Road_Condition_Icy', 'categorical__Road_Condition_Under Construction', 'categorical__Road_Condition_Wet', 'categorical__Vehicle_Type_Bicycle', 'categorical__Vehicle_Type_Bus', 'categorical__Vehicle_Type_Car', 'categorical__Vehicle_Type_Motorcycle', 'categorical__Vehicle_Type_Truck', 'categorical__Traffic_Density_High', 'categorical__Traffic_Density_Low', 'categorical__Traffic_Density_Moderate', 'categorical__Time_Period_Afternoon', 'categorical__Time_Period_Evening', 'categorical__Time_Period_Late Evening', 'categorical__Time_Period_Morning', 'categorical__Time_Period_Night', 'categorical__Peak_Hour_Non-Peak', 'categorical__Peak_Hour_Peak', 'categorical__Day_Name_Friday', 'categorical__Day_Name_Monday', 'categorical__Day_Name_Saturday', 'categorical__Day_Name_Sunday', 'categorical__Day_Name_Thursday', 'categorical__Day_Name_Tuesday', 'categorical__Day_Name_Wednesday', 'numerical__Hour', 'numerical__Month', 'numerical__Is_Weekend', 'numerical__Number_of_Vehicles']

In [ ]:
# ============================================================
# STEP 93: TRAIN RANDOM FOREST MODEL
# ============================================================

from sklearn.ensemble import RandomForestClassifier

# Create Random Forest classifier
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

# Train model
rf_model.fit(
    X_train_encoded,
    y_train
)

# Generate predictions
y_train_pred = rf_model.predict(X_train_encoded)
y_test_pred = rf_model.predict(X_test_encoded)

# Generate probability predictions
y_test_proba = rf_model.predict_proba(X_test_encoded)[:, 1]

print("=" * 70)
print("RANDOM FOREST MODEL")
print("=" * 70)

print("\nModel Training Completed Successfully.")

print("\nNumber of Trees:")
print(rf_model.n_estimators)

print("\nNumber of Training Records:")
print(X_train_encoded.shape[0])

print("\nNumber of Testing Records:")
print(X_test_encoded.shape[0])

print("\nNumber of Features:")
print(X_train_encoded.shape[1])

print("\nSample Predictions:")
print(y_test_pred[:20])

print("\nSample High-Risk Probabilities:")
print(y_test_proba[:20].round(3))

======================================================================
RANDOM FOREST MODEL
======================================================================

Model Training Completed Successfully.

Number of Trees:
200

Number of Training Records:
4000

Number of Testing Records:
1000

Number of Features:
40

Sample Predictions:
[1 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0]

Sample High-Risk Probabilities:
[0.52  0.45  0.395 0.325 0.48  0.545 0.375 0.445 0.675 0.575 0.42  0.545
 0.58  0.505 0.685 0.38  0.36  0.715 0.32  0.46 ]

In [ ]:
# ============================================================
# STEP 94: EVALUATE RANDOM FOREST MODEL
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Training performance
train_accuracy = accuracy_score(
    y_train,
    y_train_pred
)

# Testing performance
test_accuracy = accuracy_score(
    y_test,
    y_test_pred
)

test_precision = precision_score(
    y_test,
    y_test_pred
)

test_recall = recall_score(
    y_test,
    y_test_pred
)

test_f1 = f1_score(
    y_test,
    y_test_pred
)

test_roc_auc = roc_auc_score(
    y_test,
    y_test_proba
)

# Confusion matrix
cm = confusion_matrix(
    y_test,
    y_test_pred
)

print("=" * 70)
print("RANDOM FOREST MODEL EVALUATION")
print("=" * 70)

print("\nTraining Accuracy:")
print(round(train_accuracy, 4))

print("\nTesting Accuracy:")
print(round(test_accuracy, 4))

print("\nTesting Precision:")
print(round(test_precision, 4))

print("\nTesting Recall:")
print(round(test_recall, 4))

print("\nTesting F1-Score:")
print(round(test_f1, 4))

print("\nTesting ROC-AUC:")
print(round(test_roc_auc, 4))

print("\nAccuracy Gap:")
print(round(train_accuracy - test_accuracy, 4))

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_test_pred,
        target_names=[
            'Lower Risk',
            'High Risk'
        ]
    )
)

======================================================================
RANDOM FOREST MODEL EVALUATION
======================================================================

Training Accuracy:
0.9998

Testing Accuracy:
0.502

Testing Precision:
0.5

Testing Recall:
0.4578

Testing F1-Score:
0.478

Testing ROC-AUC:
0.5121

Accuracy Gap:
0.4978

Confusion Matrix:
[[274 228]
 [270 228]]

Classification Report:
              precision    recall  f1-score   support

  Lower Risk       0.50      0.55      0.52       502
   High Risk       0.50      0.46      0.48       498

    accuracy                           0.50      1000
   macro avg       0.50      0.50      0.50      1000
weighted avg       0.50      0.50      0.50      1000

In [ ]:
# ============================================================
# STEP 95: LOGISTIC REGRESSION BASELINE MODEL
# ============================================================

from sklearn.linear_model import LogisticRegression

# Create Logistic Regression model
lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight='balanced'
)

# Train model
lr_model.fit(
    X_train_encoded,
    y_train
)

# Predictions
lr_train_pred = lr_model.predict(X_train_encoded)
lr_test_pred = lr_model.predict(X_test_encoded)

# Probability predictions
lr_test_proba = lr_model.predict_proba(X_test_encoded)[:, 1]

print("=" * 70)
print("LOGISTIC REGRESSION BASELINE")
print("=" * 70)

print("\nModel Training Completed Successfully.")

print("\nTraining Accuracy:")
print(round(
    accuracy_score(y_train, lr_train_pred), 4
))

print("\nTesting Accuracy:")
print(round(
    accuracy_score(y_test, lr_test_pred), 4
))

print("\nTesting Precision:")
print(round(
    precision_score(y_test, lr_test_pred), 4
))

print("\nTesting Recall:")
print(round(
    recall_score(y_test, lr_test_pred), 4
))

print("\nTesting F1-Score:")
print(round(
    f1_score(y_test, lr_test_pred), 4
))

print("\nTesting ROC-AUC:")
print(round(
    roc_auc_score(y_test, lr_test_proba), 4
))

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        lr_test_pred
    )
)

======================================================================
LOGISTIC REGRESSION BASELINE
======================================================================

Model Training Completed Successfully.

Training Accuracy:
0.5445

Testing Accuracy:
0.549

Testing Precision:
0.5499

Testing Recall:
0.5201

Testing F1-Score:
0.5346

Testing ROC-AUC:
0.5568

Confusion Matrix:
[[290 212]
 [239 259]]

In [ ]:
# ============================================================
# STEP 95: RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

# Extract feature importance from the trained Random Forest
feature_importance_df = pd.DataFrame({
    'Feature': encoded_feature_names,
    'Importance': rf_model.feature_importances_
})

# Sort by importance
feature_importance_df = feature_importance_df.sort_values(
    by='Importance',
    ascending=False
).reset_index(drop=True)

print("=" * 70)
print("RANDOM FOREST FEATURE IMPORTANCE")
print("=" * 70)

print("\nTop 15 Most Important Features:")
display(
    feature_importance_df.head(15)
)

print("\nBottom 10 Least Important Features:")
display(
    feature_importance_df.tail(10)
)

print("\nTotal Feature Importance:")
print(
    round(feature_importance_df['Importance'].sum(), 4)
)

======================================================================
RANDOM FOREST FEATURE IMPORTANCE
======================================================================

Top 15 Most Important Features:

                                           Feature  Importance
0                                  numerical__Hour    0.111011
1                                 numerical__Month    0.098337
2                    numerical__Number_of_Vehicles    0.066463
3            categorical__Traffic_Density_Moderate    0.025213
4                categorical__Traffic_Density_High    0.025065
5                 categorical__Traffic_Density_Low    0.023521
6                  categorical__Road_Condition_Icy    0.023477
7                  categorical__Road_Condition_Dry    0.023451
8           categorical__Location_Residential Zone    0.023364
9                  categorical__Road_Condition_Wet    0.023312
10  categorical__Road_Condition_Under Construction    0.022976
11              categorical__Weather_Condition_Fog    0.022823
12             categorical__Weather_Condition_Snow    0.022527
13                   categorical__Location_Highway    0.022420
14             categorical__Weather_Condition_Rain    0.022183

Bottom 10 Least Important Features:

                                  Feature  Importance
30                  numerical__Is_Weekend    0.016745
31       categorical__Time_Period_Morning    0.016040
32     categorical__Time_Period_Afternoon    0.015171
33           categorical__Day_Name_Sunday    0.013629
34        categorical__Peak_Hour_Non-Peak    0.013435
35         categorical__Day_Name_Saturday    0.013370
36         categorical__Time_Period_Night    0.013070
37            categorical__Peak_Hour_Peak    0.012595
38       categorical__Time_Period_Evening    0.012140
39  categorical__Time_Period_Late Evening    0.010716

Total Feature Importance:
1.0

In [ ]:
# ============================================================
# STEP 96: PRE-EVENT ACCIDENT RISK MODEL
# ============================================================

# Remove post-event variable
pre_event_features = [
    'Location',
    'Weather_Condition',
    'Road_Condition',
    'Vehicle_Type',
    'Traffic_Density',
    'Hour',
    'Time_Period',
    'Peak_Hour',
    'Month',
    'Day_Name',
    'Is_Weekend'
]

X_pre = risk_df[pre_event_features].copy()
y_pre = risk_df['High_Risk'].copy()

# Identify categorical and numerical features
pre_event_categorical = [
    'Location',
    'Weather_Condition',
    'Road_Condition',
    'Vehicle_Type',
    'Traffic_Density',
    'Time_Period',
    'Peak_Hour',
    'Day_Name'
]

pre_event_numerical = [
    'Hour',
    'Month',
    'Is_Weekend'
]

# Preprocessing
pre_event_preprocessor = ColumnTransformer(
    transformers=[
        (
            'categorical',
            OneHotEncoder(
                handle_unknown='ignore',
                sparse_output=False
            ),
            pre_event_categorical
        ),
        (
            'numerical',
            'passthrough',
            pre_event_numerical
        )
    ]
)

# Train-test split
X_pre_train, X_pre_test, y_pre_train, y_pre_test = train_test_split(
    X_pre,
    y_pre,
    test_size=0.20,
    random_state=42,
    stratify=y_pre
)

# Encode
X_pre_train_encoded = pre_event_preprocessor.fit_transform(
    X_pre_train
)

X_pre_test_encoded = pre_event_preprocessor.transform(
    X_pre_test
)

# Logistic Regression
pre_event_model = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight='balanced'
)

pre_event_model.fit(
    X_pre_train_encoded,
    y_pre_train
)

# Predictions
pre_event_pred = pre_event_model.predict(
    X_pre_test_encoded
)

pre_event_proba = pre_event_model.predict_proba(
    X_pre_test_encoded
)[:, 1]

# Evaluation
pre_event_accuracy = accuracy_score(
    y_pre_test,
    pre_event_pred
)

pre_event_precision = precision_score(
    y_pre_test,
    pre_event_pred
)

pre_event_recall = recall_score(
    y_pre_test,
    pre_event_pred
)

pre_event_f1 = f1_score(
    y_pre_test,
    pre_event_pred
)

pre_event_auc = roc_auc_score(
    y_pre_test,
    pre_event_proba
)

print("=" * 70)
print("PRE-EVENT ACCIDENT RISK MODEL")
print("=" * 70)

print("\nFeatures Used:")
print(pre_event_features)

print("\nNumber of Original Features:")
print(len(pre_event_features))

print("\nEncoded Feature Count:")
print(X_pre_train_encoded.shape[1])

print("\nTraining Records:")
print(X_pre_train_encoded.shape[0])

print("\nTesting Records:")
print(X_pre_test_encoded.shape[0])

print("\nModel Performance:")
print("Accuracy :", round(pre_event_accuracy, 4))
print("Precision:", round(pre_event_precision, 4))
print("Recall   :", round(pre_event_recall, 4))
print("F1-Score :", round(pre_event_f1, 4))
print("ROC-AUC  :", round(pre_event_auc, 4))

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_pre_test,
        pre_event_pred
    )
)

======================================================================
PRE-EVENT ACCIDENT RISK MODEL
======================================================================

Features Used:
['Location', 'Weather_Condition', 'Road_Condition', 'Vehicle_Type', 'Traffic_Density', 'Hour', 'Time_Period', 'Peak_Hour', 'Month', 'Day_Name', 'Is_Weekend']

Number of Original Features:
11

Encoded Feature Count:
39

Training Records:
4000

Testing Records:
1000

Model Performance:
Accuracy : 0.535
Precision: 0.5347
Recall   : 0.51
F1-Score : 0.5221
ROC-AUC  : 0.551

Confusion Matrix:
[[281 221]
 [244 254]]

In [ ]:
# ============================================================
# STEP 97: PRE-EVENT MODEL FEATURE IMPORTANCE
# ============================================================

# Get encoded feature names
pre_event_feature_names = (
    pre_event_preprocessor
    .get_feature_names_out()
)

# Extract model coefficients
pre_event_coefficients = (
    pre_event_model
    .coef_[0]
)

# Create feature importance dataframe
pre_event_importance = pd.DataFrame({
    'Feature': pre_event_feature_names,
    'Coefficient': pre_event_coefficients,
    'Absolute_Importance': np.abs(pre_event_coefficients)
})

# Sort by absolute coefficient magnitude
pre_event_importance = (
    pre_event_importance
    .sort_values(
        'Absolute_Importance',
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("PRE-EVENT MODEL FEATURE IMPORTANCE")
print("=" * 70)

print("\nTop 15 Features:")
display(
    pre_event_importance.head(15)
)

print("\nBottom 10 Features:")
display(
    pre_event_importance.tail(10)
)

print("\nTotal Encoded Features:")
print(len(pre_event_importance))

======================================================================
PRE-EVENT MODEL FEATURE IMPORTANCE
======================================================================

Top 15 Features:

                                  Feature  Coefficient  Absolute_Importance
0          categorical__Time_Period_Night     0.331066             0.331066
1   categorical__Time_Period_Late Evening    -0.305038             0.305038
2        categorical__Time_Period_Evening    -0.259559             0.259559
3        categorical__Time_Period_Morning     0.217765             0.217765
4         categorical__Vehicle_Type_Truck    -0.180151             0.180151
5    categorical__Weather_Condition_Storm    -0.162567             0.162567
6      categorical__Time_Period_Afternoon    -0.139230             0.139230
7   categorical__Location_Industrial Area     0.138799             0.138799
8          categorical__Location_Downtown    -0.117797             0.117797
9         categorical__Peak_Hour_Non-Peak    -0.117622             0.117622
10         categorical__Day_Name_Thursday    -0.103747             0.103747
11        categorical__Road_Condition_Wet    -0.099995             0.099995
12          categorical__Location_Highway    -0.096966             0.096966
13         categorical__Day_Name_Saturday     0.094565             0.094565
14        categorical__Road_Condition_Icy    -0.091750             0.091750

Bottom 10 Features:

,Feature,Coefficient,Absolute_Importance
29,categorical__Vehicle_Type_Bus,0.025736,0.025736
30,categorical__Day_Name_Sunday,-0.025554,0.025554
31,categorical__Location_Residential Zone,-0.019135,0.019135
32,categorical__Day_Name_Wednesday,0.017762,0.017762
33,categorical__Vehicle_Type_Motorcycle,-0.011410,0.011410
34,categorical__Traffic_Density_Moderate,-0.008989,0.008989
35,categorical__Vehicle_Type_Bicycle,0.006791,0.006791
36,numerical__Month,-0.005495,0.005495
37,categorical__Vehicle_Type_Car,0.004038,0.004038
38,categorical__Road_Condition_Under Construction,0.000527,0.000527

Total Encoded Features:
39

In [ ]:
# ============================================================
# STEP 98: MODEL PERFORMANCE COMPARISON
# ============================================================

# Random Forest metrics
rf_accuracy = accuracy_score(y_test, y_test_pred)
rf_precision = precision_score(y_test, y_test_pred)
rf_recall = recall_score(y_test, y_test_pred)
rf_f1 = f1_score(y_test, y_test_pred)
rf_auc = roc_auc_score(y_test, y_test_proba)

# Logistic Regression metrics
lr_accuracy = accuracy_score(y_test, lr_test_pred)
lr_precision = precision_score(y_test, lr_test_pred)
lr_recall = recall_score(y_test, lr_test_pred)
lr_f1 = f1_score(y_test, lr_test_pred)
lr_auc = roc_auc_score(y_test, lr_test_proba)

# Pre-event Logistic Regression metrics
comparison_df = pd.DataFrame({
    'Model': [
        'Random Forest',
        'Logistic Regression',
        'Pre-Event Logistic Regression'
    ],
    'Accuracy': [
        rf_accuracy,
        lr_accuracy,
        pre_event_accuracy
    ],
    'Precision': [
        rf_precision,
        lr_precision,
        pre_event_precision
    ],
    'Recall': [
        rf_recall,
        lr_recall,
        pre_event_recall
    ],
    'F1_Score': [
        rf_f1,
        lr_f1,
        pre_event_f1
    ],
    'ROC_AUC': [
        rf_auc,
        lr_auc,
        pre_event_auc
    ]
})

# Round metrics
metric_columns = [
    'Accuracy',
    'Precision',
    'Recall',
    'F1_Score',
    'ROC_AUC'
]

comparison_df[metric_columns] = (
    comparison_df[metric_columns].round(4)
)

print("=" * 70)
print("MODEL PERFORMANCE COMPARISON")
print("=" * 70)

display(comparison_df)

print("\nBest ROC-AUC:")
best_auc_index = comparison_df['ROC_AUC'].idxmax()

print(
    comparison_df.loc[
        best_auc_index,
        ['Model', 'ROC_AUC']
    ].to_dict()
)

======================================================================
MODEL PERFORMANCE COMPARISON
======================================================================

,Model,Accuracy,Precision,Recall,F1_Score,ROC_AUC
0,Random Forest,0.502,0.5000,0.4578,0.4780,0.5121
1,Logistic Regression,0.549,0.5499,0.5201,0.5346,0.5568
2,Pre-Event Logistic Regression,0.535,0.5347,0.5100,0.5221,0.5510

Best ROC-AUC:
{'Model': 'Logistic Regression', 'ROC_AUC': 0.5568}

In [ ]:
# ============================================================
# STEP 99: ROC CURVE ANALYSIS
# ============================================================

from sklearn.metrics import roc_curve, auc

# Calculate ROC curves
rf_fpr, rf_tpr, _ = roc_curve(
    y_test,
    y_test_proba
)

lr_fpr, lr_tpr, _ = roc_curve(
    y_test,
    lr_test_proba
)

pre_event_fpr, pre_event_tpr, _ = roc_curve(
    y_pre_test,
    pre_event_proba
)

# Calculate AUC values
rf_roc_auc = auc(rf_fpr, rf_tpr)
lr_roc_auc = auc(lr_fpr, lr_tpr)
pre_event_roc_auc = auc(
    pre_event_fpr,
    pre_event_tpr
)

print("=" * 70)
print("ROC CURVE ANALYSIS")
print("=" * 70)

print("\nRandom Forest ROC-AUC:")
print(round(rf_roc_auc, 4))

print("\nLogistic Regression ROC-AUC:")
print(round(lr_roc_auc, 4))

print("\nPre-Event Logistic Regression ROC-AUC:")
print(round(pre_event_roc_auc, 4))

print("\nROC Curve Data Prepared Successfully.")

print("\nRandom Forest Points:", len(rf_fpr))
print("Logistic Regression Points:", len(lr_fpr))
print("Pre-Event Logistic Regression Points:", len(pre_event_fpr))

======================================================================
ROC CURVE ANALYSIS
======================================================================

Random Forest ROC-AUC:
0.5121

Logistic Regression ROC-AUC:
0.5568

Pre-Event Logistic Regression ROC-AUC:
0.551

ROC Curve Data Prepared Successfully.

Random Forest Points: 106
Logistic Regression Points: 519
Pre-Event Logistic Regression Points: 510

In [ ]:
# ============================================================
# STEP 100: GENERATE PREDICTED RISK PROBABILITIES
# ============================================================

# Encode the complete pre-event dataset
X_pre_encoded = pre_event_preprocessor.transform(X_pre)

# Generate probability of High Risk
risk_probability = pre_event_model.predict_proba(
    X_pre_encoded
)[:, 1]

# Create prediction dataframe
risk_predictions = risk_df.copy()

risk_predictions['Predicted_Risk_Probability'] = (
    risk_probability
)

# Convert probability into a simple risk category
risk_predictions['Predicted_Risk_Category'] = pd.cut(
    risk_predictions['Predicted_Risk_Probability'],
    bins=[-0.01, 0.33, 0.66, 1.00],
    labels=['Low', 'Medium', 'High']
)

print("=" * 70)
print("PREDICTED ACCIDENT RISK OUTPUT")
print("=" * 70)

print("\nTotal Records:")
print(len(risk_predictions))

print("\nRisk Probability Statistics:")
print(
    risk_predictions[
        'Predicted_Risk_Probability'
    ].describe().round(4)
)

print("\nPredicted Risk Category Distribution:")
print(
    risk_predictions[
        'Predicted_Risk_Category'
    ].value_counts()
    .sort_index()
)

print("\nSample Predictions:")
display(
    risk_predictions[
        [
            'Location',
            'Weather_Condition',
            'Road_Condition',
            'Vehicle_Type',
            'Traffic_Density',
            'Hour',
            'Time_Period',
            'Peak_Hour',
            'Predicted_Risk_Probability',
            'Predicted_Risk_Category'
        ]
    ].head(10)
)

======================================================================
PREDICTED ACCIDENT RISK OUTPUT
======================================================================

Total Records:
5000

Risk Probability Statistics:
count    5000.0000
mean        0.4995
std         0.0488
min         0.3343
25%         0.4667
50%         0.4990
75%         0.5318
max         0.6790
Name: Predicted_Risk_Probability, dtype: float64

Predicted Risk Category Distribution:
Predicted_Risk_Category
Low          0
Medium    4998
High         2
Name: count, dtype: int64

Sample Predictions:

,Location,Weather_Condition,Road_Condition,Vehicle_Type,Traffic_Density,Hour,Time_Period,Peak_Hour,Predicted_Risk_Probability,Predicted_Risk_Category
0,Suburbs,Fog,Icy,Bus,Low,0,Night,Non-Peak,0.432081,Medium
1,Downtown,Clear,Icy,Bus,Low,1,Night,Non-Peak,0.458469,Medium
2,Residential Zone,Snow,Dry,Motorcycle,Moderate,2,Night,Non-Peak,0.527210,Medium
3,Downtown,Fog,Icy,Bicycle,Moderate,3,Night,Non-Peak,0.461490,Medium
4,Highway,Storm,Under Construction,Bus,High,4,Night,Non-Peak,0.466975,Medium
5,Suburbs,Clear,Wet,Car,Moderate,5,Night,Non-Peak,0.523898,Medium
6,Suburbs,Storm,Icy,Motorcycle,Moderate,6,Morning,Non-Peak,0.446703,Medium
7,Downtown,Fog,Wet,Car,Low,7,Morning,Peak,0.468599,Medium
8,Suburbs,Rain,Dry,Bicycle,High,8,Morning,Peak,0.544075,Medium
9,Highway,Clear,Dry,Bus,High,9,Morning,Peak,0.571910,Medium

In [ ]:
# ============================================================
# STEP 101: DATA-DRIVEN RISK BANDS
# ============================================================

# Calculate percentile-based thresholds
low_threshold = (
    risk_predictions[
        'Predicted_Risk_Probability'
    ].quantile(0.33)
)

high_threshold = (
    risk_predictions[
        'Predicted_Risk_Probability'
    ].quantile(0.67)
)

# Create data-driven risk bands
risk_predictions['Risk_Band'] = pd.cut(
    risk_predictions['Predicted_Risk_Probability'],
    bins=[
        -np.inf,
        low_threshold,
        high_threshold,
        np.inf
    ],
    labels=[
        'Lower Risk',
        'Medium Risk',
        'Higher Risk'
    ]
)

print("=" * 70)
print("DATA-DRIVEN RISK BAND ANALYSIS")
print("=" * 70)

print("\nLower Risk Threshold:")
print(round(low_threshold, 4))

print("\nHigher Risk Threshold:")
print(round(high_threshold, 4))

print("\nRisk Band Distribution:")
print(
    risk_predictions[
        'Risk_Band'
    ].value_counts()
    .sort_index()
)

print("\nRisk Band Percentages:")
print(
    (
        risk_predictions['Risk_Band']
        .value_counts(normalize=True)
        .sort_index()
        * 100
    ).round(2)
)

print("\nRisk Band Probability Summary:")

risk_band_summary = (
    risk_predictions
    .groupby(
        'Risk_Band',
        observed=False
    )['Predicted_Risk_Probability']
    .agg(
        Count='count',
        Minimum='min',
        Average='mean',
        Maximum='max'
    )
    .round(4)
)

display(risk_band_summary)

======================================================================
DATA-DRIVEN RISK BAND ANALYSIS
======================================================================

Lower Risk Threshold:
0.4776

Higher Risk Threshold:
0.5198

Risk Band Distribution:
Risk_Band
Lower Risk     1650
Medium Risk    1700
Higher Risk    1650
Name: count, dtype: int64

Risk Band Percentages:
Risk_Band
Lower Risk     33.0
Medium Risk    34.0
Higher Risk    33.0
Name: proportion, dtype: float64

Risk Band Probability Summary:

             Count  Minimum  Average  Maximum
Risk_Band
Lower Risk    1650   0.3343   0.4462   0.4775
Medium Risk   1700   0.4776   0.4989   0.5198
Higher Risk   1650   0.5199   0.5535   0.6790

In [ ]:
# ============================================================
# STEP 102: HIGHER-RISK ANALYSIS BY LOCATION
# ============================================================

location_risk = (
    risk_predictions
    .groupby('Location')
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        ),
        Average_Higher_Risk_Probability=(
            'Predicted_Risk_Probability',
            lambda x: x[x >= high_threshold].mean()
        )
    )
    .reset_index()
)

# Calculate percentage of higher-risk records
location_risk['Higher_Risk_Percentage'] = (
    location_risk['Higher_Risk_Records']
    / location_risk['Total_Records']
    * 100
)

# Round values
location_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = location_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by higher-risk percentage
location_risk = (
    location_risk
    .sort_values(
        'Higher_Risk_Percentage',
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTED RISK ANALYSIS BY LOCATION")
print("=" * 70)

display(location_risk)

======================================================================
PREDICTED RISK ANALYSIS BY LOCATION
======================================================================

,Location,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Average_Higher_Risk_Probability,Higher_Risk_Percentage
0,Industrial Area,993,651,0.5396,0.5652,65.5589
1,Residential Zone,998,366,0.5024,0.5485,36.6733
2,Suburbs,1017,255,0.4921,0.5442,25.0737
3,Highway,1018,200,0.4846,0.5467,19.6464
4,Downtown,974,178,0.4792,0.5420,18.2752

In [ ]:
# ============================================================
# STEP 103: PREDICTED RISK ANALYSIS BY TIME PERIOD
# ============================================================

time_risk = (
    risk_predictions
    .groupby('Time_Period')
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        ),
        Average_Higher_Risk_Probability=(
            'Predicted_Risk_Probability',
            lambda x: x[x >= high_threshold].mean()
        )
    )
    .reset_index()
)

# Calculate percentage of higher-risk records
time_risk['Higher_Risk_Percentage'] = (
    time_risk['Higher_Risk_Records']
    / time_risk['Total_Records']
    * 100
)

# Round values
time_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = time_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by time period
time_order = [
    'Night',
    'Morning',
    'Afternoon',
    'Evening',
    'Late Evening'
]

time_risk['Time_Period'] = pd.Categorical(
    time_risk['Time_Period'],
    categories=time_order,
    ordered=True
)

time_risk = (
    time_risk
    .sort_values('Time_Period')
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTED RISK ANALYSIS BY TIME PERIOD")
print("=" * 70)

display(time_risk)

======================================================================
PREDICTED RISK ANALYSIS BY TIME PERIOD
======================================================================

,Time_Period,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Average_Higher_Risk_Probability,Higher_Risk_Percentage
0,Night,1254,273,0.4844,0.5487,21.7703
1,Morning,1250,660,0.5230,0.5581,52.8000
2,Afternoon,1040,176,0.4781,0.5457,16.9231
3,Evening,832,301,0.5055,0.5510,36.1779
4,Late Evening,624,240,0.5107,0.5553,38.4615

In [ ]:
# ============================================================
# STEP 104: PREDICTED RISK ANALYSIS BY WEATHER CONDITION
# ============================================================

weather_risk = (
    risk_predictions
    .groupby('Weather_Condition')
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        ),
        Average_Higher_Risk_Probability=(
            'Predicted_Risk_Probability',
            lambda x: x[x >= high_threshold].mean()
        )
    )
    .reset_index()
)

# Calculate percentage of higher-risk records
weather_risk['Higher_Risk_Percentage'] = (
    weather_risk['Higher_Risk_Records']
    / weather_risk['Total_Records']
    * 100
)

# Round values
weather_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = weather_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by higher-risk percentage
weather_risk = (
    weather_risk
    .sort_values(
        'Higher_Risk_Percentage',
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTED RISK ANALYSIS BY WEATHER CONDITION")
print("=" * 70)

display(weather_risk)

======================================================================
PREDICTED RISK ANALYSIS BY WEATHER CONDITION
======================================================================

,Weather_Condition,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Average_Higher_Risk_Probability,Higher_Risk_Percentage
0,Clear,1019,511,0.5227,0.5584,50.1472
1,Snow,1001,428,0.5145,0.5563,42.7572
2,Rain,1054,332,0.4986,0.5501,31.4991
3,Fog,969,270,0.4933,0.5487,27.8638
4,Storm,957,109,0.4667,0.5420,11.3898

In [ ]:
# ============================================================
# STEP 105: PREDICTED RISK ANALYSIS BY ROAD CONDITION
# ============================================================

road_risk = (
    risk_predictions
    .groupby('Road_Condition')
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        ),
        Average_Higher_Risk_Probability=(
            'Predicted_Risk_Probability',
            lambda x: x[x >= high_threshold].mean()
        )
    )
    .reset_index()
)

# Calculate percentage of higher-risk records
road_risk['Higher_Risk_Percentage'] = (
    road_risk['Higher_Risk_Records']
    / road_risk['Total_Records']
    * 100
)

# Round values
road_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = road_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by higher-risk percentage
road_risk = (
    road_risk
    .sort_values(
        'Higher_Risk_Percentage',
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTED RISK ANALYSIS BY ROAD CONDITION")
print("=" * 70)

display(road_risk)

======================================================================
PREDICTED RISK ANALYSIS BY ROAD CONDITION
======================================================================

,Road_Condition,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Average_Higher_Risk_Probability,Higher_Risk_Percentage
0,Dry,1257,575,0.5158,0.5571,45.7438
1,Under Construction,1222,513,0.5103,0.5539,41.9804
2,Icy,1288,291,0.4873,0.5485,22.5932
3,Wet,1233,271,0.4852,0.5507,21.9789

In [ ]:
# ============================================================
# STEP 106: PREDICTED RISK ANALYSIS BY TRAFFIC DENSITY
# ============================================================

density_risk = (
    risk_predictions
    .groupby('Traffic_Density')
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        ),
        Average_Higher_Risk_Probability=(
            'Predicted_Risk_Probability',
            lambda x: x[x >= high_threshold].mean()
        )
    )
    .reset_index()
)

# Calculate percentage of higher-risk records
density_risk['Higher_Risk_Percentage'] = (
    density_risk['Higher_Risk_Records']
    / density_risk['Total_Records']
    * 100
)

# Round values
density_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = density_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort logically by traffic density
density_order = [
    'Low',
    'Moderate',
    'High'
]

density_risk['Traffic_Density'] = pd.Categorical(
    density_risk['Traffic_Density'],
    categories=density_order,
    ordered=True
)

density_risk = (
    density_risk
    .sort_values('Traffic_Density')
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTED RISK ANALYSIS BY TRAFFIC DENSITY")
print("=" * 70)

display(density_risk)

======================================================================
PREDICTED RISK ANALYSIS BY TRAFFIC DENSITY
======================================================================

,Traffic_Density,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Average_Higher_Risk_Probability,Higher_Risk_Percentage
0,Low,1603,405,0.4884,0.5490,25.2651
1,Moderate,1710,690,0.5105,0.5573,40.3509
2,High,1687,555,0.4990,0.5521,32.8986

In [ ]:
# ============================================================
# STEP 107: PREDICTED RISK ANALYSIS BY VEHICLE TYPE
# ============================================================

vehicle_risk = (
    risk_predictions
    .groupby('Vehicle_Type')
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        ),
        Average_Higher_Risk_Probability=(
            'Predicted_Risk_Probability',
            lambda x: x[x >= high_threshold].mean()
        )
    )
    .reset_index()
)

# Calculate percentage of higher-risk records
vehicle_risk['Higher_Risk_Percentage'] = (
    vehicle_risk['Higher_Risk_Records']
    / vehicle_risk['Total_Records']
    * 100
)

# Round values
vehicle_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = vehicle_risk[
    [
        'Average_Risk_Probability',
        'Average_Higher_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by higher-risk percentage
vehicle_risk = (
    vehicle_risk
    .sort_values(
        'Higher_Risk_Percentage',
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTED RISK ANALYSIS BY VEHICLE TYPE")
print("=" * 70)

display(vehicle_risk)

======================================================================
PREDICTED RISK ANALYSIS BY VEHICLE TYPE
======================================================================

,Vehicle_Type,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Average_Higher_Risk_Probability,Higher_Risk_Percentage
0,Bus,956,395,0.5135,0.5566,41.3180
1,Car,1032,406,0.5091,0.5534,39.3411
2,Bicycle,988,382,0.5077,0.5535,38.6640
3,Motorcycle,972,360,0.5057,0.5531,37.0370
4,Truck,1052,107,0.4642,0.5440,10.1711

In [ ]:
# ============================================================
# STEP 108: OVERALL PREDICTIVE RISK PROFILE
# ============================================================

risk_profile = (
    risk_predictions
    .groupby(
        [
            'Location',
            'Time_Period',
            'Weather_Condition',
            'Road_Condition',
            'Traffic_Density',
            'Vehicle_Type'
        ]
    )
    .agg(
        Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        )
    )
    .reset_index()
)

# Calculate Higher Risk percentage
risk_profile['Higher_Risk_Percentage'] = (
    risk_profile['Higher_Risk_Records']
    / risk_profile['Records']
    * 100
)

# Round values
risk_profile[
    [
        'Average_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = risk_profile[
    [
        'Average_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by average predicted risk
risk_profile = (
    risk_profile
    .sort_values(
        [
            'Average_Risk_Probability',
            'Higher_Risk_Percentage'
        ],
        ascending=False
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("OVERALL PREDICTIVE RISK PROFILE")
print("=" * 70)

print("\nTotal Risk Profiles:")
print(len(risk_profile))

print("\nTop 20 Risk Profiles:")
display(
    risk_profile.head(20)
)

print("\nRisk Profile Summary:")
print(
    risk_profile[
        [
            'Records',
            'Higher_Risk_Records',
            'Average_Risk_Probability',
            'Higher_Risk_Percentage'
        ]
    ].describe().round(4)
)

======================================================================
OVERALL PREDICTIVE RISK PROFILE
======================================================================

Total Risk Profiles:
3591

Top 20 Risk Profiles:

,Location,Time_Period,Weather_Condition,Road_Condition,Traffic_Density,Vehicle_Type,Records,Higher_Risk_Records,Average_Risk_Probability,Higher_Risk_Percentage
0,Industrial Area,Morning,Clear,Dry,Moderate,Car,1,1,0.6790,100.0
1,Industrial Area,Late Evening,Clear,Dry,Moderate,Bus,1,1,0.6681,100.0
2,Industrial Area,Morning,Clear,Icy,Moderate,Bus,1,1,0.6521,100.0
3,Industrial Area,Morning,Clear,Dry,Moderate,Motorcycle,1,1,0.6391,100.0
4,Industrial Area,Afternoon,Clear,Under Construction,Moderate,Bus,1,1,0.6380,100.0
5,Industrial Area,Late Evening,Clear,Icy,Moderate,Car,1,1,0.6366,100.0
6,Industrial Area,Morning,Clear,Dry,High,Bus,1,1,0.6360,100.0
7,Industrial Area,Morning,Clear,Under Construction,Moderate,Car,2,2,0.6352,100.0
8,Industrial Area,Evening,Snow,Dry,High,Car,1,1,0.6349,100.0
9,Industrial Area,Late Evening,Snow,Dry,Low,Motorcycle,1,1,0.6325,100.0
10,Industrial Area,Morning,Snow,Under Construction,Moderate,Bicycle,1,1,0.6325,100.0
11,Industrial Area,Morning,Rain,Under Construction,Low,Motorcycle,1,1,0.6287,100.0
12,Industrial Area,Evening,Clear,Dry,Moderate,Motorcycle,1,1,0.6284,100.0
13,Industrial Area,Late Evening,Snow,Dry,Moderate,Bicycle,1,1,0.6250,100.0
14,Industrial Area,Morning,Snow,Under Construction,High,Bus,2,2,0.6244,100.0
15,Downtown,Morning,Clear,Dry,Moderate,Bus,1,1,0.6237,100.0
16,Industrial Area,Morning,Rain,Under Construction,Moderate,Bus,1,1,0.6230,100.0
17,Highway,Morning,Clear,Under Construction,Moderate,Bus,1,1,0.6228,100.0
18,Industrial Area,Late Evening,Clear,Under Construction,Moderate,Car,1,1,0.6224,100.0
19,Industrial Area,Morning,Clear,Dry,Moderate,Bicycle,2,2,0.6215,100.0

Risk Profile Summary:
         Records  Higher_Risk_Records  Average_Risk_Probability  \
count  3591.0000            3591.0000                 3591.0000
mean      1.3924               0.4595                    0.4996
std       0.6714               0.6913                    0.0473
min       1.0000               0.0000                    0.3491
25%       1.0000               0.0000                    0.4676
50%       1.0000               0.0000                    0.4991
75%       2.0000               1.0000                    0.5305
max       6.0000               4.0000                    0.6790

       Higher_Risk_Percentage
count               3591.0000
mean                  33.0010
std                   45.1961
min                    0.0000
25%                    0.0000
50%                    0.0000
75%                  100.0000
max                  100.0000

In [ ]:
# ============================================================
# STEP 109: PREDICTIVE RISK BY LOCATION AND TIME PERIOD
# ============================================================

location_time_risk = (
    risk_predictions
    .groupby(
        [
            'Location',
            'Time_Period'
        ]
    )
    .agg(
        Total_Records=('Risk_Band', 'size'),
        Higher_Risk_Records=(
            'Risk_Band',
            lambda x: (x == 'Higher Risk').sum()
        ),
        Average_Risk_Probability=(
            'Predicted_Risk_Probability',
            'mean'
        )
    )
    .reset_index()
)

# Calculate Higher Risk percentage
location_time_risk['Higher_Risk_Percentage'] = (
    location_time_risk['Higher_Risk_Records']
    / location_time_risk['Total_Records']
    * 100
)

# Round values
location_time_risk[
    [
        'Average_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = location_time_risk[
    [
        'Average_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Sort by location and time period
time_order = [
    'Night',
    'Morning',
    'Afternoon',
    'Evening',
    'Late Evening'
]

location_time_risk['Time_Period'] = pd.Categorical(
    location_time_risk['Time_Period'],
    categories=time_order,
    ordered=True
)

location_time_risk = (
    location_time_risk
    .sort_values(
        [
            'Location',
            'Time_Period'
        ]
    )
    .reset_index(drop=True)
)

print("=" * 70)
print("PREDICTIVE RISK BY LOCATION AND TIME PERIOD")
print("=" * 70)

display(location_time_risk)

print("\nHighest Higher-Risk Location-Time Groups:")
display(
    location_time_risk
    .sort_values(
        'Higher_Risk_Percentage',
        ascending=False
    )
    .head(10)
)

======================================================================
PREDICTIVE RISK BY LOCATION AND TIME PERIOD
======================================================================

,Location,Time_Period,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Higher_Risk_Percentage
0,Downtown,Night,251,18,0.4621,7.1713
1,Downtown,Morning,234,87,0.5044,37.1795
2,Downtown,Afternoon,212,16,0.4592,7.5472
3,Downtown,Evening,168,36,0.4886,21.4286
4,Downtown,Late Evening,109,21,0.4885,19.2661
5,Highway,Night,246,24,0.4653,9.7561
6,Highway,Morning,263,100,0.5067,38.0228
7,Highway,Afternoon,192,11,0.4670,5.7292
8,Highway,Evening,170,34,0.4901,20.0000
9,Highway,Late Evening,147,31,0.4938,21.0884
10,Industrial Area,Night,258,133,0.5233,51.5504
11,Industrial Area,Morning,240,203,0.5649,84.5833
12,Industrial Area,Afternoon,203,95,0.5192,46.7980
13,Industrial Area,Evening,160,119,0.5446,74.3750
14,Industrial Area,Late Evening,132,101,0.5508,76.5152
15,Residential Zone,Night,249,54,0.4876,21.6867
16,Residential Zone,Morning,260,163,0.5287,62.6923
17,Residential Zone,Afternoon,215,29,0.4753,13.4884
18,Residential Zone,Evening,167,70,0.5095,41.9162
19,Residential Zone,Late Evening,107,50,0.5165,46.7290
20,Suburbs,Night,250,44,0.4825,17.6000
21,Suburbs,Morning,253,107,0.5116,42.2925
22,Suburbs,Afternoon,218,25,0.4707,11.4679
23,Suburbs,Evening,167,42,0.4966,25.1497
24,Suburbs,Late Evening,129,37,0.5031,28.6822

Highest Higher-Risk Location-Time Groups:

,Location,Time_Period,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Higher_Risk_Percentage
11,Industrial Area,Morning,240,203,0.5649,84.5833
14,Industrial Area,Late Evening,132,101,0.5508,76.5152
13,Industrial Area,Evening,160,119,0.5446,74.3750
16,Residential Zone,Morning,260,163,0.5287,62.6923
10,Industrial Area,Night,258,133,0.5233,51.5504
12,Industrial Area,Afternoon,203,95,0.5192,46.7980
19,Residential Zone,Late Evening,107,50,0.5165,46.7290
21,Suburbs,Morning,253,107,0.5116,42.2925
18,Residential Zone,Evening,167,70,0.5095,41.9162
6,Highway,Morning,263,100,0.5067,38.0228

In [ ]:
# ============================================================
# STEP 110: EXPORT PREDICTIVE RESULTS FOR POWER BI
# ============================================================

# Create final predictive dataset
predictive_output = risk_predictions.copy()

# Keep relevant fields for Power BI
predictive_output = predictive_output[
    [
        'Location',
        'Weather_Condition',
        'Road_Condition',
        'Vehicle_Type',
        'Traffic_Density',
        'Hour',
        'Time_Period',
        'Peak_Hour',
        'Month',
        'Day_Name',
        'Is_Weekend',
        'Number_of_Vehicles',
        'Accident_Severity',
        'Accident_Severity_Score',
        'High_Risk',
        'Predicted_Risk_Probability',
        'Risk_Band'
    ]
].copy()

# Round predicted probability
predictive_output[
    'Predicted_Risk_Probability'
] = predictive_output[
    'Predicted_Risk_Probability'
].round(4)

# Export CSV
predictive_output.to_csv(
    '/content/Accident_Risk_Predictions.csv',
    index=False
)

print("=" * 70)
print("PREDICTIVE OUTPUT EXPORT")
print("=" * 70)

print("\nRows exported:")
print(len(predictive_output))

print("\nColumns exported:")
print(list(predictive_output.columns))

print("\nRisk Band Distribution:")
print(
    predictive_output['Risk_Band']
    .value_counts()
    .sort_index()
)

print("\nFile created:")
print("/content/Accident_Risk_Predictions.csv")

print("\nPreview:")
display(
    predictive_output.head(10)
)

======================================================================
PREDICTIVE OUTPUT EXPORT
======================================================================

Rows exported:
5000

Columns exported:
['Location', 'Weather_Condition', 'Road_Condition', 'Vehicle_Type', 'Traffic_Density', 'Hour', 'Time_Period', 'Peak_Hour', 'Month', 'Day_Name', 'Is_Weekend', 'Number_of_Vehicles', 'Accident_Severity', 'Accident_Severity_Score', 'High_Risk', 'Predicted_Risk_Probability', 'Risk_Band']

Risk Band Distribution:
Risk_Band
Lower Risk     1650
Medium Risk    1700
Higher Risk    1650
Name: count, dtype: int64

File created:
/content/Accident_Risk_Predictions.csv

Preview:

,Location,Weather_Condition,Road_Condition,Vehicle_Type,Traffic_Density,Hour,Time_Period,Peak_Hour,Month,Day_Name,Is_Weekend,Number_of_Vehicles,Accident_Severity,Accident_Severity_Score,High_Risk,Predicted_Risk_Probability,Risk_Band
0,Suburbs,Fog,Icy,Bus,Low,0,Night,Non-Peak,1,Monday,False,2,Minor,1,0,0.4321,Lower Risk
1,Downtown,Clear,Icy,Bus,Low,1,Night,Non-Peak,1,Monday,False,2,Minor,1,0,0.4585,Lower Risk
2,Residential Zone,Snow,Dry,Motorcycle,Moderate,2,Night,Non-Peak,1,Monday,False,4,Moderate,2,0,0.5272,Higher Risk
3,Downtown,Fog,Icy,Bicycle,Moderate,3,Night,Non-Peak,1,Monday,False,3,Moderate,2,0,0.4615,Lower Risk
4,Highway,Storm,Under Construction,Bus,High,4,Night,Non-Peak,1,Monday,False,4,Moderate,2,0,0.4670,Lower Risk
5,Suburbs,Clear,Wet,Car,Moderate,5,Night,Non-Peak,1,Monday,False,2,Fatal,4,1,0.5239,Higher Risk
6,Suburbs,Storm,Icy,Motorcycle,Moderate,6,Morning,Non-Peak,1,Monday,False,4,Moderate,2,0,0.4467,Lower Risk
7,Downtown,Fog,Wet,Car,Low,7,Morning,Peak,1,Monday,False,2,Moderate,2,0,0.4686,Lower Risk
8,Suburbs,Rain,Dry,Bicycle,High,8,Morning,Peak,1,Monday,False,2,Moderate,2,0,0.5441,Higher Risk
9,Highway,Clear,Dry,Bus,High,9,Morning,Peak,1,Monday,False,3,Severe,3,1,0.5719,Higher Risk

In [ ]:
# ============================================================
# STEP 111: EXPORT LOCATION × TIME PREDICTIVE SUMMARY
# ============================================================

# Create a Power BI-ready summary
predictive_location_time = location_time_risk.copy()

# Convert categorical Time_Period back to normal text
predictive_location_time['Time_Period'] = (
    predictive_location_time['Time_Period']
    .astype(str)
)

# Round values for dashboard use
predictive_location_time[
    [
        'Average_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
] = predictive_location_time[
    [
        'Average_Risk_Probability',
        'Higher_Risk_Percentage'
    ]
].round(4)

# Export
predictive_location_time.to_csv(
    '/content/Predictive_Risk_Location_Time.csv',
    index=False
)

print("=" * 70)
print("LOCATION × TIME PREDICTIVE SUMMARY EXPORT")
print("=" * 70)

print("\nRows exported:")
print(len(predictive_location_time))

print("\nFile created:")
print("/content/Predictive_Risk_Location_Time.csv")

print("\nSummary:")
display(predictive_location_time)

print("\nHighest Higher-Risk Location-Time Groups:")
display(
    predictive_location_time
    .sort_values(
        'Higher_Risk_Percentage',
        ascending=False
    )
    .head(10)
)

======================================================================
LOCATION × TIME PREDICTIVE SUMMARY EXPORT
======================================================================

Rows exported:
25

File created:
/content/Predictive_Risk_Location_Time.csv

Summary:

,Location,Time_Period,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Higher_Risk_Percentage
0,Downtown,Night,251,18,0.4621,7.1713
1,Downtown,Morning,234,87,0.5044,37.1795
2,Downtown,Afternoon,212,16,0.4592,7.5472
3,Downtown,Evening,168,36,0.4886,21.4286
4,Downtown,Late Evening,109,21,0.4885,19.2661
5,Highway,Night,246,24,0.4653,9.7561
6,Highway,Morning,263,100,0.5067,38.0228
7,Highway,Afternoon,192,11,0.4670,5.7292
8,Highway,Evening,170,34,0.4901,20.0000
9,Highway,Late Evening,147,31,0.4938,21.0884
10,Industrial Area,Night,258,133,0.5233,51.5504
11,Industrial Area,Morning,240,203,0.5649,84.5833
12,Industrial Area,Afternoon,203,95,0.5192,46.7980
13,Industrial Area,Evening,160,119,0.5446,74.3750
14,Industrial Area,Late Evening,132,101,0.5508,76.5152
15,Residential Zone,Night,249,54,0.4876,21.6867
16,Residential Zone,Morning,260,163,0.5287,62.6923
17,Residential Zone,Afternoon,215,29,0.4753,13.4884
18,Residential Zone,Evening,167,70,0.5095,41.9162
19,Residential Zone,Late Evening,107,50,0.5165,46.7290
20,Suburbs,Night,250,44,0.4825,17.6000
21,Suburbs,Morning,253,107,0.5116,42.2925
22,Suburbs,Afternoon,218,25,0.4707,11.4679
23,Suburbs,Evening,167,42,0.4966,25.1497
24,Suburbs,Late Evening,129,37,0.5031,28.6822

Highest Higher-Risk Location-Time Groups:

,Location,Time_Period,Total_Records,Higher_Risk_Records,Average_Risk_Probability,Higher_Risk_Percentage
11,Industrial Area,Morning,240,203,0.5649,84.5833
14,Industrial Area,Late Evening,132,101,0.5508,76.5152
13,Industrial Area,Evening,160,119,0.5446,74.3750
16,Residential Zone,Morning,260,163,0.5287,62.6923
10,Industrial Area,Night,258,133,0.5233,51.5504
12,Industrial Area,Afternoon,203,95,0.5192,46.7980
19,Residential Zone,Late Evening,107,50,0.5165,46.7290
21,Suburbs,Morning,253,107,0.5116,42.2925
18,Residential Zone,Evening,167,70,0.5095,41.9162
6,Highway,Morning,263,100,0.5067,38.0228

In [ ]:
# ============================================================
# STEP 112: FINAL OUTPUT FILE INVENTORY
# ============================================================

import os

output_files = [
    'Dim_Date.csv',
    'Dim_Time.csv',
    'Dim_Weather.csv',
    'Dim_Road_Condition.csv',
    'Dim_Vehicle_Type.csv',
    'Fact_Traffic.csv',
    'Fact_Accident.csv',
    'Accident_Risk_Predictions.csv',
    'Predictive_Risk_Location_Time.csv'
]

print("=" * 70)
print("FINAL PROJECT OUTPUT FILE INVENTORY")
print("=" * 70)

file_status = []

for file_name in output_files:
    file_path = f'/content/{file_name}'

    if os.path.exists(file_path):
        file_size_kb = os.path.getsize(file_path) / 1024

        file_status.append({
            'File': file_name,
            'Status': 'Available',
            'Size_KB': round(file_size_kb, 2)
        })
    else:
        file_status.append({
            'File': file_name,
            'Status': 'Missing',
            'Size_KB': 0
        })

output_inventory = pd.DataFrame(file_status)

display(output_inventory)

print("\nAvailable Files:")
print(
    (output_inventory['Status'] == 'Available').sum(),
    "of",
    len(output_inventory)
)

print("\nMissing Files:")
print(
    (output_inventory['Status'] == 'Missing').sum()
)

======================================================================
FINAL PROJECT OUTPUT FILE INVENTORY
======================================================================

                                File     Status  Size_KB
0                       Dim_Date.csv  Available    10.42
1                       Dim_Time.csv  Available     0.91
2                    Dim_Weather.csv  Available     0.06
3             Dim_Road_Condition.csv  Available     0.07
4               Dim_Vehicle_Type.csv  Available     0.07
5                   Fact_Traffic.csv  Available    26.09
6                  Fact_Accident.csv  Available   400.51
7      Accident_Risk_Predictions.csv  Available   506.12
8  Predictive_Risk_Location_Time.csv  Available     1.13

Available Files:
9 of 9

Missing Files:
0